### ISSUE TITLE
FPL API: Max retries exceeded with url

### ISSUE THREAD

**Issue by mazhar-debug** [alan-turing-institute/AIrsenal#119]
I've been trying to setup the AIrsenal database now since yesterday, and I seem to always run into this error:
`HTTPSConnectionPool(host='fantasy.premierleague.com', port=443): Max retries exceeded with url`

In fill_playerscore_table.py I've done some sleep-experimenting. Adding a sleep(0.5) in the following location seem to help, but I still got the error. I am currenctly trying with 1 second delay.
`session.add(ps)
sleep(1)
print(
      "  got {} points vs {} in gameweek  {}".format(
         result["total_points"], opponent, gameweek
        )
)`

**Comment by mazhar-debug** [comment]
Unfortunately, not even a 1 second delay solves this.

**Comment by mazhar-debug** [comment]
Works with a 2 second delay.

**Comment by nbarlowATI** [comment]
Hi @mazhar-debug thanks for reporting this!   
I haven't seen it before, so I wonder if it was some problem on the FPL server..?
I don't think that adding a sleep before adding the individual playerscores to the database should make all that much difference, as the actual call to the FPL API only happens once per player, before this loop over matches...  

But maybe it could be good to put a check on the status code in the data_fetcher.py `get_gameweek_data_for_player` function, and if it's a 443, then sleep for a couple of seconds at that point?    
(Pull requests very welcome! :-) )
