### ISSUE TITLE
_picke.PicklingError on Windows

### ISSUE THREAD

**Issue by mazhar-debug** [alan-turing-institute/AIrsenal#120]
`_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session`

This is the error I am getting when running this on a Windows computer. There's no difference between sqlite and postgresql; both give the same error.

Any idea on where to look for a fix?

**Comment by jack89roberts** [comment]
This is the same as #165 , which we don't have a fix for at the moment unfortunately. It's related to differences in how the multiprocessing library works on Unix and Windows.
