### ISSUE TITLE
Default Database Path Doesn't Exist on Windows

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#134]
Travis builds on Windows (see #128) give the following error:
```
E   sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
E   (Background on this error at: http://sqlalche.me/e/e3q8)
```
I believe this is because our default database location is `/tmp/data.db` (or `/tmp/test.db` for tests),  which are paths that don't exist on Windows.

Possible solutions:
* Have an OS-dependent default database location, e.g. if we're on windows put it in `C:\some\temporary\directory`.
* Store the database in the airsenal directory structure, e.g. `airsenal/data/data.db`, and add that file path to `.gitignore`.

**Comment by Tomos88** [comment]
Hey folks, newbie here. I'm getting this exact error on Windows, could someone lend me a hand in getting around it? Cheers!

**Comment by jack89roberts** [comment]
Hi @Tomos88 We have a workaround on another branch (still need to decide what the permanent solution is). Assuming you've previously setup everything as described in the readme, doing these two steps from within the `AIrsenal` directory with the `airsenalenv` virtual environment activated should hopefully give you a working installation:

```bash
> git checkout fix/128-travis-windows
> pip install --upgrade --force-reinstall .
```

**Comment by Tomos88** [comment]
That worked, thank you!
