### ISSUE TITLE
Error running update_airsenal_database from fresh install 

### ISSUE THREAD

**Issue by jozzya** [alan-turing-institute/AIrsenal#137]
I am getting an error when trying to update the airsenal database, my guess is that the database did not install properly or I am not using a specific version of pip.
Any help would be much appreciated. :)

**Environment details:**

- OS - Mac OSX
- PIP Version - pip 19.3.1 from /opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/pip (python 3.7)
- Python version - 3.7.5

Error in terminal when running `update_airsenal_database`
```
 update_airsenal_database

Traceback (most recent call last):
  File "/opt/anaconda3/envs/airsenalenv/bin/update_airsenal_database", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/update_results_transactions_db.py", line 32, in main
    last_in_db = get_last_gameweek_in_db(season, session)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/utils.py", line 739, in get_last_gameweek_in_db
    .order_by(Fixture.gameweek).all()[-1]
IndexError: list index out of range
```
The only error in my installation is the following:

```
(airsenalenv) ➜  AIrsenal git:(master) ✗ pip install .
Processing /Users/username/Desktop/fantasyleague/AIrsenal
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for file:///Users/username/Desktop/fantasyleague/AIrsenal.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel
```

**Comment by jack89roberts** [comment]
Hi @jozzya - have you run `setup_airsenal_database` first? That script creates the database, which is needed for `update_airsenal_database` to work. I get the same error on my system if I don't have a database present.

Or if you have tried running that previously can you try removing the old database(if it exists) and then recreating it by doing:
```
rm /tmp/data.db
setup_airsenal_database
update_airsenal_database
```

**Comment by jozzya** [comment]
Deleting the db and re-installing seems to have done the trick. Thank you. 👍
