### ISSUE TITLE
Optimization seems to get stuck on strategies containing 3 transfers per gameweek

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#153]
Currently running `run_airsenal_optimization` and it has been going for > half an hour, with strategies "031", "030", and "003" not having moved from about halfway through - it looks like they are stuck in a loop.  
Evaluating 3 transfers per gameweek is done in a non-deterministic way - randomly removing and adding players.  It's possible that because of the low value of our team it's finding it hard to find a viable team.  Perhaps we should set a cap on number of attempts.

**Comment by nbarlowATI** [comment]
Should have mentioned that I first observed this in branch 117-player-attributes , which seems to be much slower in general for optimization than master.
However, master does also seem to occasionally get stuck on a 3-transfer week as well...

**Comment by jack89roberts** [comment]
I was having issues with strategies freezing in some of the previous iterations of fiddling with how the API requests work - is it possible you were running on an older version of the 117-player-attributes branch?

**Comment by jack89roberts** [comment]
We no longer compute 3-transfer strategies (maybe we should try again...)
