### ISSUE TITLE
Persistent player_id for multiple seasons

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#166]
To be able to have a persistent database (even one that works for the duration of a single season) we probably need another type of player id. Currently we:

* Use the FPL IDs for all the players returned by the API at the moment we run `setup_airsenal_database`, which are values from 1 to n_players.
* Increment the max id by 1 for each player we add from the history files who isn't currently active.

As soon as a new player is added to the game this fails as the new id given by the API will be the same as one we already gave to someone else. At that point we need to delete and recreate the database (or worse we don't and a current player ends up with the history of a different player?)

One approach could be to add the FPL ID to the player attributes table, and use some generic id (or maybe just the player's name) for the main players table. Related issue is how to distinguish between two players with the same name (or identify the same player with different name spellings), see #90 .

Related issue: #138

**Comment by nbarlowATI** [comment]
Could introduce a new attribute - something like "api_id"  (nullable, for past players) to handle interactions with the API for current players - keep the current player_id as the primary key.
