### ISSUE TITLE
Covid-19 disruption

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#180]
To keep a list of issues that the disruption to the season due to Covid-19 may cause for the AIrsenal code.

- Hard-coded values:
  - Number of gameweeks per season.
    - Dealt with in 05589cc , though in places only by increasing hardcoded max possible values to 100.
  - Dates of season, i.e. what season we're in based on the current month and year.
    - Fixed in 9099062, but only to update transition date from July to August.

- API:
  - Tests have started failing due to a problem with `data_fetcher.get_fpl_team_history_data`.
    - Maybe some updates FPL were doing during lockdown, tests are passing now.

- `get_recent_minutes` defaults to using an average of the previous season if no matches played in the last 3 gameweeks.
  - Fixed in 8fa7bdd: Return values from the most recent gameweek available in the DB (and the two gameweeks before that). A longer-term average (from this season) probably would be better, as e.g. pre-lockdown injuries unlikely to be relevant now.

- `get_next_gameweek` always returns 39 if no fixtures are scheduled.
  - Fixed in 05589cc7 and 0f4a0bf0 to use max gameweek in DB + 1, or 100 where DB not available.

- Data checks: Allowing 5 substitutes means the number of players check in `airsenal_check_data` comes back with a lot of errors (fails if it finds more than 14 players made an appearance for a team in a match).
  - Fixed in #333

**Comment by jack89roberts** [comment]
I've been running everything on the [117-player-attributes](https://github.com/alan-turing-institute/AIrsenal/tree/117-player-attributes) branch, which seems to be working ok.

Checked the master branch and `run_airsenal_predictions` is giving an error due to a None datetime value somewhere.

**Comment by jack89roberts** [comment]
Allowing 5 subsitutes means the number of players check in `airsenal_check_data` comes back with a lot of errors.

**Comment by jack89roberts** [comment]
Players with blank gameweek 1 don't have their starting price available in the normal place in the API (#244)

**Comment by biggins** [comment]
Hi @jack89roberts stumbled across the issue when trying to narrow down why the checks were failing for this season. 

Was wondering if the project wanted pull requests to account for the one-off rule changes?

**Comment by jack89roberts** [comment]
Hi @biggins , yes definitely - we're always happy to get pull requests! The only remaining issue* for the checks is the 5 substitutes change post-lockdown (and based on the comments above, those fixtures should have gameweek values of 39 or above in the database). It's still possible that 5 substitutes will be re-introduced this season, so would be nice if the solution can deal with multiple periods where 5 substitutes were allowed. Happy to help with any questions 🙂

_(* only Covid-19 related issue, there's another check that fails due to duplicate player names, see https://github.com/alan-turing-institute/AIrsenal/issues/62#issuecomment-533303584)_

**Comment by biggins** [comment]
Hi @jack89roberts, 

Have created a pull request to address the players issue, there is another integrity issue that I haven't looked into yet
`==================================================

Checking sum of player goals equals match results...

1819 GW4 CAR 2-3 ARS (id 721): Player scores sum to 1 but 2 goals in result for home team

 FAIL! 1 errors.

==================================================`

**Comment by jack89roberts** [comment]
Great, thanks @biggins ! I'll take a look at the PR later. The remaining error is because there were two different players called Danny Ward in the 2018/19 season. There's not a separate issue for it but it's mentioned in #90 and #62.

FPL doesn't have a persistent ID for players (each player's ID changes every season), so we link players to their histories using their names. That works fine until you have multiple players with the same name...
