### ISSUE TITLE
Make all entrypoints start with "airsenal"

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#202]
To help disambiguate with other applications users may have installed, we should probably modify all our entrypoints so that they start with "airsenal_", and then have something short and descriptive to help find the desired command via tab-completion.  
e.g. something like:
* ```airsenal_setup_initial_db```
* ```airsenal_update_db```
* ```airsenal_dump_db```
* ```airsenal_check_data```
* ```airsenal_make_team```
* ```airsenal_run_prediction```
* ```airsenal_run_optimization```

This would just involve modifying the `entry_points` dict in `setup.py`.

**Comment by callistusndemo** [comment]
Hey @nbarlowATI - I just discovered this project as I prepare my FPL strategy for the next season. I'm not familiar with the code base but I can implement the changes you suggested above. I'm new to open source contributions but curious to learn, let me know if I can help with this. Cheers.

**Comment by nbarlowATI** [comment]
Hi @callistusndemo - fantastic!  Yes, it would be great if you could help with this!  Hopefully this change is pretty straightforward, but if this gets you hooked into possibly using and improving the rest of the codebase then our cunning plan has worked! :-P 

If you would like to do this, the best thing would be to fork the repo to your profile, then change to the "develop" branch:
```
git checkout develop
```
then make the changes, commit them, and then make a pull request back into this repo.   

Once FPL announces the players/prices for next season then hopefully AIrsenal will work out-of-the-box with predictions and suggestions.   We're currently working on making it able to "replay" past seasons, which would make it easier for new users to try things out in the meantime, but we're not quite there yet.

Anyway, thanks again, and let me know if you have any trouble!

**Comment by callistusndemo** [comment]
Thanks, @nbarlowATI. I'm interested in technical documentation (#101) so I just may :) I'll get started on this and trouble you with any questions I may have along the way. 

Thanks again for the opportunity.

**Comment by callistusndemo** [comment]
Thanks, @nbarlowATI. I'm interested in technical documentation (#101). So, I just may :) I'll get started on this and trouble you with any questions I may have along the way. 

Thanks again for the opportunity.
