### ISSUE TITLE
Add "season" column to FifaTeamRating table

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#205]
If we want to be able to replay past seasons, we should start with the appropriate year's FIFA ratings for that season in order to get the same prior as we did when initially running.

This should just involve:
 * adding a "season" Column to the FifaTeamRating class in `airsenal/framework/schema.py`
 * adding a line to fill the season attribute in `airsenal/scripts/fill_fifa_ratings_table.py`
 * adding a "season" argument to the function definition `get_ratings_df` in `airsenal/framework/bpl_interface.py` and using it in a filter when doing the db query (as is done in e.g. `get_next_gameweek` in `airsenal/framework/utils.py`).

**Comment by jack89roberts** [comment]
@nbarlowATI This is already done on the 169-replay-season branch (in the WIP PR #171), from what I remember.

**Comment by nbarlowATI** [comment]
Hi @jack89roberts , ah, good point!!    
I came across this as I just ran the script to dump the db contents, and added the resulting csv files in the branch `feature/203-add-csv-data` (thought it was best to do this before this last season's data disappeared from the API!) and saw the season info was missing for the FIFA ratings.
But it's good to know that past-us had the same thinking as present-us! :)

I'll see if I can find a bit of time to get the 169-replay-season branch up-to-date and .... maybe even replaying a season(!) ... in the next few days...  If that does prove to be tough though, it might still be worth making this small change on top of the current `develop` anyway, just so we have everything as ready as can be for the start of next season...

**Comment by jack89roberts** [comment]
I think it got to the point where the prediction code should work starting as if it was any season or gameweek, but I don't think we'd started on the optimisation code yet. Maybe we could check it and merge as is, and leave the optimisation for another PR?

Getting a single optimisation to run based on those predictions might not be much more work though? Running a full season (or stitching together multiple predictions and optimisations) is maybe where the biggest chunk of work is.
