### ISSUE TITLE
Hardcoded season causes tests to fail when current season changes

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#209]
The season is hardcoded in the tests in two places:
- `fill_players()` in `fixtures.py`
- `TEST_SEASON` in `test_team.py`

If these values don't match the value of `CURRENT_SEASON` in the main package, which is used as a default value in many functions, the tests fail.

Quick fix would be to set `TEST_SEASON` to `CURRENT_SEASON` (available in `airsenal.framework.utils`). Alternatively, set the season to `TEST_SEASON` correctly in all the functions that the tests call.

**Comment by pratyushpal** [comment]
Hey! Just wanted to get started and be involved in the community! Is anyone working on this issue yet?

**Comment by jack89roberts** [comment]
Hi! I don't think so, if you'd like to do this that would be great! 🙂
