### ISSUE TITLE
Fix flake8 errors

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#227]
flake8 checks the code against style guidelines. 

To install it: 
```
pip install flake8
```

To run, change to the parent "AIrsenal" directory on your system and run:
```
flake8 --max-line-length=88 --count
```
(The default line length limit is 79 characters, but we use the black linter which uses 88 characters).

This currently returns around 640 errors (includes things like unused imports, blank lines with whitespace etc.).

Start to fix these (and maybe add flake8 to our test suite).

**Comment by pratyushpal** [comment]
Gonna pick this up!
