### ISSUE TITLE
Initial setup issue 

### ISSUE THREAD

**Issue by saba83rish** [alan-turing-institute/AIrsenal#229]
The read me says 
`Once you've installed the module, you will need to set some environment variables (or alternatively you can put the values into files in the airsenal/data/ directory, e.g. airsenal/data/FPL_TEAM_ID:`
What would be the name of the file?
I tried creating the file name as <my_fpl_id>.
Inside the file as well i created a variable FPL_TEAM_ID=<my_fpl_id>
Still I see this `Couldn't find FPL_TEAM_ID - some data may be unavailable`
Could you be more specific in the README file please?

**Comment by connorlhgs** [comment]
I've just tried setting everything up and have run into the same issue. Did you resolve this?

**Comment by jack89roberts** [comment]
Hi @saba83rish , the file should literally be called "FPL_TEAM_ID", and as its contents it should contain your team ID and nothing else.

So the file is `airsenal/data/FPL_TEAM_ID` and its contents are something like:
```
123456789
```
I'll update the readme to hopefully be more helpful.

Note that the team ID won't actually be used until after the season has started.

**Comment by Hughesy** [comment]
I followed all the instructions to the letter, but I keep getting the error "zsh: command not found: airsenal_setup_initial_db" when i try to build the database. Can someone tell me what I am doing wrong? Thanks

**Comment by Hughesy** [comment]
> I followed all the instructions to the letter, but I keep getting the error "zsh: command not found: airsenal_setup_initial_db" when i try to build the database. Can someone tell me what I am doing wrong? Thanks

Its definitely something to do with my path, but i can't work out whats causing the issue.

**Comment by jack89roberts** [comment]
@Hughesy If you installed AIrsenal in a conda environment have you activated it?

To activate: `conda activate airsenalenv` If it's activated `which python` should then return a path with `airsenalenv` in it.

If that still doesn't work could you try importing airsenal in a python shell:
```
python
>>> import airsenal
```

Does that work?

**Comment by Hughesy** [comment]
> @Hughesy If you installed AIrsenal in a conda environment have you activated it?
> 
> To activate: `conda activate airsenalenv` If it's activated `which python` should then return a path with `airsenalenv` in it.
> 
> If `airsenal_setup_initial_db` still doesn't work after activating the environment could you try importing airsenal in a python shell:
> 
> ```
> python
> >>> import airsenal
> ```
> 
> Does that work?

When I activate the conda environment I get the attached. Is this right?
<img width="500" alt="Screenshot 2020-09-03 at 11 56 20" src="https://user-images.githubusercontent.com/2457878/92106586-8816b900-eddc-11ea-8fec-e36c3f7f75cf.png">

**Comment by jack89roberts** [comment]
Deleted comments have been moved to #233

**Comment by jack89roberts** [comment]
I believe this is resolved but feel free to re-open (or make a new issue) if you're still having problems.
