### ISSUE TITLE
Click and black package file incompatibility

### ISSUE THREAD

**Issue by RobWHickman** [alan-turing-institute/AIrsenal#235]
(at least on windows) Click 7.1.2 needed for black, but the requirements files require click==7.0,

simple fix just to change the req to at least version 7.0 which might be worth considering (or even just updating the req to 7.1.2)

**Comment by jack89roberts** [comment]
Thanks @RobWHickman , I'm definitely happy to accept the simple fix you propose to the Click version - would you like to make the change and create a pull request for it?

Note that we do have other problems on Windows (e.g. #165), the only workaround we currently have to get everything working is to use the Windows Subsystem for Linux instead.

**Comment by RobWHickman** [comment]
sure-  I'll set Click to at least 7.0 and that can always be amended if it doesn't fix it 👍 

Yeah hitting the same-ish problems, is there an issue/resolution/pull/etc. on the WSL fix?

**Comment by jack89roberts** [comment]
Thanks for the PR. It's not really a fix, installing WSL basically lets you run AIrsenal on Linux but from your Windows machine (see here for WSL docs: https://docs.microsoft.com/en-us/windows/wsl/).

I'd like to fix the underlying problem but it's some tricky sqlalchemy/multiprocessing issue specific to Windows that I have no idea how to solve (and we mostly develop this on Macs so don't get to test it on Windows much). You say same-ish though, is the error you're getting different to the one in that issue?
