### ISSUE TITLE
Fixture data for upcoming season

### ISSUE THREAD

**Issue by ryanwilliams90** [alan-turing-institute/AIrsenal#240]
I have been looking at https://github.com/alan-turing-institute/AIrsenal/blob/master/airsenal/data/fixtures.csv and the other fixture files within /data and I do not see the new fixtures for the upcoming season 20/21. I am guessing this is correct from references of that file in code.

Is this correct and needs updated or am I looking in the wrong place?

**Comment by jack89roberts** [comment]
Hi @ryanwilliams90 , thanks for the question. We have some old files sitting in the repo that need to be tidied up, including the fixtures file you linked. The fixture data for 20/21 is taken directly from the FPL API and then stored in the AIrsenal database.

If you have already setup the database (with `airsenal_setup_initial_db`) you can get a list of fixtures for any gameweek this season by doing the following in a python shell:
```python
from airsenal.framework.utils import *
print(get_fixtures_for_gameweek(1))
```
This should return something like:
```python
[('FUL', 'ARS'), ('CRY', 'SOU'), ('LIV', 'LEE'), ('WHU', 'NEW'), ('WBA', 'LEI'), ('TOT', 'EVE'), ('SHU', 'WOL'), ('BHA', 'CHE')]
```

**Comment by rwilliams-r7** [comment]
Thank you makes perfect sense.
