### ISSUE TITLE
airsenal_run_optimization --weeks_ahead 3 error

### ISSUE THREAD

**Issue by Hughesy** [alan-turing-institute/AIrsenal#245]
Trying to run `airsenal_run_optimization --weeks_ahead 3`, but I keep getting the attached error. All the FPL league and team IDs are all correct and located in the right place.[
<img width="566" alt="Screenshot 2020-09-15 at 10 04 59" src="https://user-images.githubusercontent.com/2457878/93190466-4fab9f00-f73b-11ea-82c0-26e0f51b57e9.png">
](url)

**Comment by jack89roberts** [comment]
Hi @Hughesy , could you try what's suggested in https://github.com/alan-turing-institute/AIrsenal/issues/244#issuecomment-692608772 and see if that fixes it for you?

If not, do you have your team ID defined either as an environment variable or in a `airsenal/data/FPL_TEAM_ID` file?

**Comment by Hughesy** [comment]
Still getting the above error when I try whats been suggested in #244.

I have the team ID located here: airsenal/data/FPL_TEAM_ID, in a file with no extension.

**Comment by jack89roberts** [comment]
Hmm ok not sure then, I'll have a think later. I'll close this issue and continue the discussion in #244 to keep things in one place.

**Comment by jack89roberts** [comment]
This is different to #244 , rather it looks more like #181 . Looks like it works fine for me with your team ID though but I'll investigate.

**Comment by jack89roberts** [comment]
@Hughesy - could you try running the lines below in a python shell or script? It will probably give you the same error.
```
from airsenal.framewoork.utils import *
team = get_starting_team()
print(team)
print("Complete:", team.is_complete())
tag = get_latest_prediction_tag()
print("Tag:", tag)
score = team.get_expected_points(2, tag)
print("Score:", score)
```

**Comment by Hughesy** [comment]
I'm getting a can't read error when I try and run the first line.

**Comment by jack89roberts** [comment]
Did you run it from within python? I've edited the code snippet above to hopefully make that clearer.

**Comment by Hughesy** [comment]
<img width="559" alt="Screenshot 2020-09-16 at 10 56 29" src="https://user-images.githubusercontent.com/2457878/93322522-4e49a780-f80b-11ea-9774-a8e205295148.png"

When i try to run it in python I get the above error regarding "get_starting_team"

**Comment by jack89roberts** [comment]
Ah sorry, I missed an import - I've updated the box above again.

**Comment by Hughesy** [comment]
I've attached the full shell, which implies that its struggling to pull through my team. Did you say that you could run the optimisation line for my team?
<img width="1186" alt="Screenshot 2020-09-16 at 11 13 24" src="https://user-images.githubusercontent.com/2457878/93324512-ed6f9e80-f80d-11ea-9daf-668599f04221.png">

**Comment by jack89roberts** [comment]
And I think you've already tried deleting, recreating and updating the database?

```
rm /tmp/data.db
airsenal_setup_initial_db
airsenal_update_db --noattr
```

If that hasn't worked can we see whether it's managing to get your team from the API:
```
conda activate airsenalenv
python

from airsenal.framework.utils import *
get_players_for_gameweek(1)

exit()
```
This should print a list of player IDs.

And also whether the database is being filled correctly:
```
sqlite3 'SELECT * FROM "transaction";'
```
This should print 15 rows (one for each player).

**Comment by Hughesy** [comment]
It seems to return an error when I ask it to pull my team from gameweek 1 too
<img width="1084" alt="Screenshot 2020-09-16 at 12 41 32" src="https://user-images.githubusercontent.com/2457878/93332671-16962c00-f81a-11ea-8f9a-016e849f6ad6.png">

**Comment by jack89roberts** [comment]
Ah it looks like the text editor you used has added some metadata to the team ID file that AIrsenal can't deal with (the URL its printed after unable to access FPL team API has a load of additional stuff where only the team ID should be). This should recreate it with the format needed (run from the parent AIrsenal directory):
```
rm airsenal/data/FPL_TEAM_ID
cat 1246844 > airsenal/data/FPL_TEAM_ID
```

If you run the whole pipeline again it should work, I hope!

**Comment by Hughesy** [comment]
When I try and run the final line, I get the error "cat: 1246844: No such file or directory". I'm running this from the AIrsenal directory.

**Comment by jack89roberts** [comment]
Bah I wrote the wrong command - it should be "echo 1246844 > airsenal/data/FPL_TEAM_ID", not cat (fixed above).

**Comment by Hughesy** [comment]
Hate to say it, but i'm still having the same issue. 

I do now have a new FPL_TEAM_ID file, in airsenal/data, so that did work.
<img width="1183" alt="Screenshot 2020-09-16 at 13 49 28" src="https://user-images.githubusercontent.com/2457878/93339403-734a1480-f823-11ea-995c-5afc28544d83.png">

**Comment by jack89roberts** [comment]
☹️ I'll revisit it this evening but could you try the bottom two boxes from https://github.com/alan-turing-institute/AIrsenal/issues/245#issuecomment-693342905 again and see if you get anything different to before?

**Comment by Hughesy** [comment]
Just revisited, however I keep getting the same errors. Thanks for helping!

**Comment by jack89roberts** [comment]
What does this give you now?
```
conda activate airsenalenv
python

from airsenal.framework.utils import *
get_players_for_gameweek(1)

exit()
```

**Comment by Hughesy** [comment]
Morning Jack, I get the attached.
<img width="1103" alt="Screenshot 2020-09-17 at 08 49 31" src="https://user-images.githubusercontent.com/2457878/93436510-cc1cba00-f8c2-11ea-9023-33f318ac5ae0.png">

**Comment by jack89roberts** [comment]
Is that definitely the updated image after re-creating the FPL_TEAM_ID file as described above? It looks like there's still some other stuff in the file. What does `cat airsenal/data/FPL_TEAM_ID` from the AIrsenal parent directory show?

**Comment by Hughesy** [comment]
Doing `cat airsenal/data/FPL_TEAM_ID` return my FPL_TEAM_ID - 1246844

**Comment by jack89roberts** [comment]
Ah maybe this is #77 where the new file isn't picked up, reinstalling AIrsenal might fix it - try doing this from the AIrsenal directory:
```
pip install --upgrade --force-reinstall .
```

Does the optimisation work after doing that?

**Comment by Hughesy** [comment]
Yes that worked! Thanks Jack!

**Comment by jack89roberts** [comment]
Great! I'll close this issue now then.

**Comment by rosseland** [comment]
I keep getting the same error, on develop branch. Force reinstalling doesnt help.
print(team) shows every player except the subs. One was from ManUtd which had no match, and 0 points for the rest of the subs.
