### ISSUE TITLE
Optimization Team is Incomplete Error

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#250]
I keep getting the same error, on develop branch. Force reinstalling doesnt help.
print(team) shows every player except the subs. One was from ManUtd which had no match, and 0 points for the rest of the subs.

_Originally posted by @rosseland in https://github.com/alan-turing-institute/AIrsenal/issues/245#issuecomment-694331330_

**Comment by rosseland** [comment]
For context:
```
 airsenal_run_optimization --weeks_ahead 3
Traceback (most recent call last):
  File "/Users/stein/opt/anaconda3/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 262, in main
    baseline_score, baseline_dict = get_baseline_prediction(num_weeks_ahead, tag)
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/framework/optimization_utils.py", line 198, in get_baseline_prediction
    score = team.get_expected_points(gw, tag)
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/framework/team.py", line 342, in get_expected_points
    raise RuntimeError("Team is incomplete")
RuntimeError: Team is incomplete
```
And 

```
>>> from airsenal.framework.utils import *
>>> from airsenal.framework.optimization_utils import *
>>> team = get_starting_team()
>>> print(team)

=== starting 11 ===


== GK ==

Kepa Arrizabalaga (CHE)
David Martin (WHU)

== DEF ==

Trent Alexander-Arnold (LIV)
John Egan (SHU)
Rúben Gonçalo Silva Nascimento Vinagre (WOL)
Luke Thomas (LEI)

== MID ==

Heung-Min Son (TOT)
Mohamed Salah (LIV)
Wilfried Zaha (CRY)
Kai Havertz (CHE)
Dale Stephens (BHA)

== FWD ==

Charlie Austin (WBA)
Timo Werner (CHE)
Raúl Jiménez (WOL)

=== subs ===


>>> print("Complete:", team.is_complete())
Complete: False
>>> tag = get_latest_prediction_tag()
>>> print("Tag:", tag)
Tag: ea48046b-c5f9-404c-9cc9-6a6189af3f9a
>>> score = team.get_expected_points(2, tag)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stein/AIrsenal/airsenal/framework/team.py", line 342, in get_expected_points
    raise RuntimeError("Team is incomplete")
RuntimeError: Team is incomplete
>>> print("Score:", score)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'score' is not defined
```

**Comment by jack89roberts** [comment]
Thanks @rosseland . It looks like it's failed to add one of your defenders - which defender from your gameweek 1 squad is missing above? If you let me know your team ID I can try to recreate the problem myself too.

**Comment by rosseland** [comment]
Right, its the United player, Brandon Williams, which obviously didnt play.
TeamID 2162740

**Comment by jack89roberts** [comment]
Weird it seems to be ok for me with your ID. Did you delete and recreate the database after installing the develop version?
```
rm /tmp/data.db
airsenal_setup_initial_db
airsenal_update_db
```
I hope `get_starting_team()` as above will give you your full squad after that, if not I'm not sure what the issue is so we'll need to find a different way to debug.

**Comment by rosseland** [comment]
I did, but I ran airsenal_run_pipeline, so i didnt notice this when running airsenal_setup_initial_db
```
Data not available for player 318 week 1
Traceback (most recent call last):
  File "/Users/stein/opt/anaconda3/bin/airsenal_setup_initial_db", line 8, in <module>
    sys.exit(main())
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/scripts/fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/framework/transaction_utils.py", line 47, in fill_initial_team
    price = gw1_data[0]["value"]
IndexError: list index out of range

```

**Comment by rosseland** [comment]
and airsenal_update_dbChecking team
```
Checking team
Traceback (most recent call last):
  File "/Users/stein/opt/anaconda3/bin/airsenal_update_db", line 8, in <module>
    sys.exit(main())
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/scripts/update_results_transactions_db.py", line 71, in main
    db_players = sorted(get_current_players(season=season, dbsession=session))
  File "/Users/stein/opt/anaconda3/lib/python3.7/site-packages/airsenal/framework/utils.py", line 193, in get_current_players
    assert len(current_players) == 15
AssertionError
```

**Comment by jack89roberts** [comment]
This looks #244 again which should be fixed on the develop branch. Could you try installing the develop branch again just in case something didn't work last time? From the AIrsenal directory with the airsenalenv environment activated:
```
rm /tmp/data.db
git checkout develop
git pull
pip install --upgrade --force-reinstall .
airsenal_setup_initial_db
```

You could do a couple of sanity checks on your local clone of the repo too - `git branch --show-current` should return "develop" and `git branch --contains 4c2eb36` should return a list including "develop".

**Comment by rosseland** [comment]
Hmm, this is strange. I am on the develop branch, and did a pull just now, latest commit is 05d75ec94a151c4b8ee8133be9ce8b33f302deb9 and no difference.


I could try on a linux machine instead of conda on mac.

**Comment by jack89roberts** [comment]
We develop it mostly on Mac so that should be the platform most likely to work! You could try trashing the whole conda environment and starting the installation from scratch (`conda remove --name airsenalenv --all -y` to delete the environment, after doing `conda deactivate` first). Installing in editable mode may also help (`pip install -e .`).

If you let me know your team ID I can test things this evening too, just in case this isn't an installation problem.

**Comment by rosseland** [comment]
cleared the conda env, updated conda, and ran again: success :)
I guess the upgrading of conda from 4.7 to 4.8 might have been essential

**Comment by jack89roberts** [comment]
Great! I'll close this issue now then but feel free to open another if you have any other problems/questions.
