### ISSUE TITLE
Unable to access Team API for players who joined after Week 1

### ISSUE THREAD

**Issue by samscnp** [alan-turing-institute/AIrsenal#257]
Hi, I am encountering a problem when trying to set up my initial database. Specifically, I received the following error message:

Unable to access FPL team API https://fantasy.premierleague.com/api/entry/6300591/event/1/picks/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airsenalenv/bin/airsenal_setup_initial_db", line 33, in <module>
    sys.exit(load_entry_point('airsenal', 'console_scripts', 'airsenal_setup_initial_db')())
  File "/Users/SamuelChan/AIrsenal/airsenal/scripts/fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "/Users/SamuelChan/AIrsenal/airsenal/framework/transaction_utils.py", line 45, in fill_initial_team
    api_players = get_players_for_gameweek(1)
  File "/Users/SamuelChan/AIrsenal/airsenal/framework/utils.py", line 626, in get_players_for_gameweek
    player_list = [p["element"] for p in player_data]
TypeError: 'NoneType' object is not iterable

-------------------------

I only created my team after Week 1 and I think that is why the program failed to load my data, which doesn't exist in Week 1. 
In my browser, when I enter "https://fantasy.premierleague.com/api/entry/6300591/event/2/picks/" instead of "https://fantasy.premierleague.com/api/entry/6300591/event/1/picks/", I am able to access my team. 

Can you please help me fix this problem? 

If it is possible, please explain to me what to do more detailedly and patiently. I am very new to programming (barely 3 months of learning). I would really appreciate it. 

Thank you very much.

**Comment by RajeshTailor1** [comment]
Try running the command with the --help switch there maybe an option to start the current season at a particularly GW for your team.

**Comment by samscnp** [comment]
thank you. I will check out your solution too.

I have made a temporary solution to change the code a little - 

in transaction_utils.py

def fill_initial_team(session, season=CURRENT_SEASON, tag="AIrsenal" + CURRENT_SEASON):
    """
    Fill the Transactions table in the database with the initial 15 players, and their costs,
    getting the information from the team history API endpoint (for the list of players in our team)
    and the player history API endpoint (for their price in gw1).
    """
    if NEXT_GAMEWEEK == 1:
        ### Season hasn't started yet - there won't be a team in the DB
        return True
    api_players = get_players_for_gameweek(2)
    for pid in api_players:
        gw1_data = fetcher.get_gameweek_data_for_player(pid, 1)
        price = gw1_data[0]["value"]
        add_transaction(pid, 1, 1, price, season, tag, session)

I changed the arguments for api_players = get_players_for_gameweek() from (1) to (2), and that seems to solve the problem.

I ran everything and everything seemed fine. I hope this small change won't mess up other parts of the program

**Comment by nbarlowATI** [comment]
Hi @samscnp you're right, this is something we hadn't considered....
It would be great (and hopefully not too difficult) to add a flag as @RajeshTailor1 suggests to use the first gameweek that a team existed.
We will be trying to flag some fixes and improvements for volunteers to work on in Hacktoberfest, and this would be a good one!

**Comment by jack89roberts** [comment]
Yes should be a good first issue - one way would be to change `airsenal.framework.transaction_utils.fill_initial_team` to try all gameweeks until it finds the first one that returns valid team data.
