### ISSUE TITLE
Could not find results for GW2

### ISSUE THREAD

**Issue by kaushalvivek** [alan-turing-institute/AIrsenal#260]
On running `airsenal_update_db`, failed to fetch results for GW2 that concluded a couple of days ago. Does it take more than two days to update the source database?

**Comment by RajeshTailor1** [comment]
When you say source database are you referring to the FPL data actually residing at Fantasy.premierleague.com? i think there data is upto date but there is an issue fetching it with the update_db command, do you have a screenshot of the actual error? 

I had an issue too but i didn't save the error but i rebuilt the database from scratch to get around this issue.

**Comment by jack89roberts** [comment]
The update probably won't work if new players have been added to the game - I think that's most likely your issue. We're working on fixing that but for now the way to get around it is to delete and recreate the database instead:
```
rm /tmp/data.db
airsenal_setup_initial_db
airsenal_update_db --noattr
```
If this doesn't fix your problem could you post the error messages you're getting?

(`airsenal_update_db` gets data directly from the FPL web-site, so the data it gets will be the same as what you see on the web-site - so it shouldn't take a long time to update)

**Comment by pratyushpal** [comment]
Running (after '1rm /tmp/data.db') airsenal_setup_initial_db gives me the following error: 

`  File "/opt/anaconda3/envs/airsenalenv/bin/airsenal_setup_initial_db", line 33, in <module>
    sys.exit(load_entry_point('airsenal', 'console_scripts', 'airsenal_setup_initial_db')())
  File "/Users/pratyushpal/AIrsenal/airsenal/scripts/fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "/Users/pratyushpal/AIrsenal/airsenal/framework/transaction_utils.py", line 47, in fill_initial_team
    price = gw1_data[0]["value"]
IndexError: list index out of range`

**Comment by kaushalvivek** [comment]
@jack89roberts , running the entire pipeline after deleting the database fixes the problem. Closing this issue since it seems to be due to new player additions.

**Comment by jack89roberts** [comment]
Great - #241 is where the fix for this is being worked on, so hopefully you won't need to do this fairly soon 🙂
