### ISSUE TITLE
Replace FPL_TEAM_ID config file with command-line arguments

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#265]
Rather than using the `data/FPL_TEAM_ID` config file, specify the team ID as part of the database setup. Then, as part of making it possible to run AIrsenal with multiple team IDs (see issue #266), make this an option for the update and optimisation scripts as well.

- Create `fpl_team_id` as a command-line argument to `main()` in `airsenal.scripts.fill_db_init.py`.
- Add `fpl_team_id` as an argument to the `fill_initial_team` function in `airsenal.framework.transaction_utils`.
- Add `fpl_team_id` as an optional argument to the `FPLDataFetcher` class. If not defined use the value of the `FPL_TEAM_ID` environment variable. If that's not defined use the last FPL team ID in the database. If nothing in the database, raise a warning. 
- In all functions that use `airsenal.framework.utils.fetcher`, or create their own `FPLDataFetcher` instance, make a new instance of FPLDataFetcher with `fpl_team_id` correctly set (probably requiring `fpl_team_id` to be added as an argument to several other functions, and then using that argument correctly where those functions are used).

**Comment by martintoreilly** [comment]
## Implementation notes
Discussion with @jack89roberts and @nbarlowATI on Fri 30 Oct 2020

**Decision:** Add optional command line argument for TEAM ID, over-riding the value in the config file if present.

Issue #266 is a natural follow on (support multiple teams).

**Comment by callummole** [comment]
See PR #322 and #334
