### ISSUE TITLE
Make it possible to run AIrsenal with multiple team IDs

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#266]
Currently, we can only store the details of one FPL team in the database at a time. The team ID is set in the `airsenal/data/FPL_TEAM_ID` configuration file, and this is used to fill the `Transaction` table in the AIrsenal database. The `Transaction` table stores a row for every player bought or sold during the season (plus the transaction purchase/sale price and gameweek). The whole contents of the `Transaction` table have to be deleted and recreated if someone wants to try running the optimisation for a different team ID .

Instead, we'd like to add `fpl_team_id` as a column to the transaction table so it can store the details of multiple teams at once. To do this:

- Add `fpl_team_id` as an integer column in the `Transaction` class in `airsenal.framework.schema`.

- Modify the `add_transaction` function in `airsenal.framework.transaction_utils` to take `fpl_team_id` as an input and include that in the created `Transaction` instance. Then modify the functions that use `add_transaction` (also in `airsenal.framework.transaction_utils`) so that they also take and use the `fpl_team_id` argument appropriately.

- Modify the `get_starting_team` function in `airsenal.framework.optimization_utils` so that it takes `fpl_team_id` as an input and use this to modify the query of the transaction table to only return rows for that `fpl_team_id`. If `fpl_team_id` is not defined the value from the last row in the `Transaction` table should be used.

-  In `airsenal.framework.utils` modify `get_current_players` and `get_sell_price_for_player` to take `fpl_team_id` and use it to modify the queries of the `Transaction` table.  As above, if `fpl_team_id` is not defined the value from the last row in the `Transaction` table should be used.

The above should make it possible to store multiple team IDs in the database. #265 will make the changes to take advantage of this.

**Comment by callummole** [comment]
Done with PR #322 and #334
