### ISSUE TITLE
Prompt for and then store FPL_LOGIN and FPL_PASSWORD values

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#268]
Similar to #265 but for the other two config files. When both are done we can remove the need for config files altogether.

`FPL_LOGIN` and `FPL_PASSWORD` are only used for plotting league standings (from memory: authentication is needed by the FPL API to return private league standings - to be verified).

Make the league standings script prompt for a username and password when needed. To do this:

- Modify the method `get_fpl_league_data` in the `FPLDataFetcher` class in `airsenal.framework.data_fetcher` so that it prompts for a username (email) and password if `self.FPL_LOGIN` and/or `self.FPL_PASSWORD` are not defined.
-  Save the values of login and password to a config file somewhere on the system (must work on all platforms).
- Have `self.FPL_LOGIN` and `self.FPL_PASSWORD` look for values in environment variable first, and the new config file second (this is done in the constructor of the `FPLDataFetcher` class at the moment).
- Add a `--reset-password` argument to `main()` in `airsenal.scripts.plot_league_standings`, and as a flag in `FPLDataFetcher.get_fpl_league_data`, which causes the user to be prompted for a new username and password even if one is already available.

**Comment by Jamespage6978** [comment]
Would a good way of doing this be using the Config Parser module instead then you have a central file that can store all config data. and you don't need to enter the data every time you run the script?

**Comment by jack89roberts** [comment]
The username and password are only used for plotting league standings, which isn't part of the core functionality and we don't think people use it very often. And the current config file setup has caused some installation issues. A good middle ground might be to prompt for username & password the first time it's used and then store that info to a config file somewhere for future use. I'll add that above.
