### ISSUE TITLE
Is airsenal_update_db still not working?

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#269]
Hi Team - apologies if I have missed this, but looks like the update db command still fails for me however I haven't recently re-installed the app.

Is there is a fix to this issue?

**Comment by jack89roberts** [comment]
If you haven't already, could you try deleting and recreating the database?
```
rm /tmp/data.db
airsenal_setup_initial_db
airsenal_update_db
```

At the moment it's always best to do this at the start of each gameweek, but we are working on making the update better (it can't deal with new players being added at the moment).

If this doesn't help, could you post the error message you're getting?

**Comment by RajeshTailor1** [comment]
Yes I’ve been deleting and recreating the database after each game week but if I recreate the database do we have to run the update straight after? Or even run the update at all?

**Comment by jack89roberts** [comment]
The initial setup just gets your gameweek 1 squad, the update should get the latest status.

**Comment by RajeshTailor1** [comment]
Ok I’ll give it a try in a few minutes and relay the results. Are there any switches I need to provide to the update command?

**Comment by jack89roberts** [comment]
If you're doing it straight after database setup you can add the `--noattr` flag to tell it not to get the latest player prices etc. (as these are already done by the setup). Will make it a bit quicker.

**Comment by RajeshTailor1** [comment]
OK great news the update command worked fine without any issues I also used the --noattr switch.  We can close this off.  Thanks for your help.
