### ISSUE TITLE
Optimization producing strange results

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#270]
Hi Team - I have run the optimization without any issues (no errors) however the results don't look right as its suggesting I remove a player in gw5 that I don't have in my team and also in gw6.  See attached screenshot.  My team id is 2585463.

![image](https://user-images.githubusercontent.com/71466307/94579173-6c35f400-0270-11eb-86ff-97a318756234.png)

**Comment by jack89roberts** [comment]
Weird, this could be related to the failed update in your other issue so let's try fixing that first.

**Comment by jack89roberts** [comment]
Yes I see the players are ones you had in gameweek 1, so this should be fixed by getting the update to work

**Comment by RajeshTailor1** [comment]
I’ll test this first thing tomorrow I wanted to ask one of the switches is Num_Iterations what does this mean?

**Comment by jack89roberts** [comment]
A few aspects of the optimisation are partially random - they try a few different possibilities and pick the best strategy from those strategies. The `--num_iterations` switch specifies how many "random" attempts it makes - large values mean it will take longer to run, but may also give better results.

This only applies to making 3 transfers in a single gameweek, wildcard teams and free hit teams. For normal strategies with 0, 1 or 2 transfers in a gameweek we attempt all possible solutions so are guaranteed to return the best result (where best means maximum predicted points).

So for normal optimisation runs changing the `--num_iterations` value won't make a difference.

**Comment by RajeshTailor1** [comment]
Thank you for explaining the Num_Iterations - much appreciated.  I'll put that to the test when I do my wildcard do you have an idea of how long it could take to run 100 iterations? (do you have any benchmarks based on running on specific systems).

Also this issue can be closed as its all working fine after running the update db command.  It was a user error :)

**Comment by jack89roberts** [comment]
Don't have good benchmarks, sorry. For a single gameweek, it's the same as running `airsenal_make_team` which has a default of 10 iterations and takes less 2 mins on my laptop (and 100 iterations will be roughly 10 times that). `airsenal_run_optimization --allow_wildcard` tries using a wildcard in the next 3 gameweek weeks so that's slower.

Someone's contributed code to make the optimisation much quicker though, so this may change soon!
