### ISSUE TITLE
Bonus points

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#28]
Find way of predicting bonus points

**Comment by callistusndemo** [comment]
[How the FPL Bonus Points System works](https://www.premierleague.com/news/106533) covers some of the stats that contribute to bonus points

**Comment by jack89roberts** [comment]
Thanks @callistusndemo ! A lot of these stats we don't have access to unfortunately, things like pass completion, big chances created/missed, tackles, errors made etc. are not things we can get from the FPL API. We do get the final BPS score for each player in each match, though. I'm not sure we have any ideas for how to model/predict the bonus points at the moment (at least I don't), so if you have any ideas that would be very helpful!
