### ISSUE TITLE
Fix Travis tests in pull requests from forks

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#285]
Some of the tests in `airsenal/tests/test_fetcher.py` currently fail in Travis CI when a pull request is made from a fork.
These tests are: 
`test_get_team_data`
`test_get_team_history_data`

This is because in the Travis setup for `alan-turing-institute/AIrsenal` we have set the environment variable FPL_TEAM_ID to something, so the data fetcher is able to get squad information from the API.

We can skip these tests, or hard-code an FPL_TEAM_ID.   My personal preference would be to skip them if:
* the file airsenal/data/FPL_TEAM_ID doesn't exist 
 AND
* the environment variable FPL_TEAM_ID isn't set 
AND (ideally)
* we are running in Travis

I'm not sure how to determine the last one though, without setting another environment variable in the Travis setup.
Perhaps the first two conditions would be enough - the tests would then not pick up the situation in local testing where the user doesn't have the FPL_TEAM_ID set correctly, but the main purpose of the tests is to test the code rather than the setup.

**Comment by Abelarm** [comment]
what if the test checks if the `airsenal/data/FPL_TEAM_ID` doesn't exist and that case SET a new environment variable just for the purpose of the test?

**Comment by nbarlowATI** [comment]
That could work, but I think it would be even easier just do set the `fetcher` object's FPL_TEAM_ID  straight after instantiating it, no need to use an environment variable.  
```
fetcher = FPLDataFetcher()
fetcher.FPL_TEAM_ID = <something> 
```
The trouble is, what team ID to choose?  It feels a bit intrusive to hard-code a team ID corresponding to an actual player's FPL team into the code...
I don't have particularly strong feelings about it though, and we could use AIrsenal's id which is 208595 (though this changes season by season)...

**Comment by Abelarm** [comment]
As you prefer, we can use the AIrsenal's one, but every year someone needs to change it.

**Comment by jack89roberts** [comment]
This doesn't fix the problem of which team ID to use but I think we could just set the team ID in `.travis.yml` as described here (rather than having it defined as a secret like it is currently):
https://docs.travis-ci.com/user/environment-variables/#defining-public-variables-in-travisyml
