### ISSUE TITLE
airsenal_make_team not working

### ISSUE THREAD

**Issue by ryanwilliams90** [alan-turing-institute/AIrsenal#287]
Hey I can see airsenal_make_team has been renamed to airsenal_make_squad but this command does not seem to work anymore. See below.....

`python3.7/site-packages/airsenal/scripts/squad_builder.py", line 87, in main
    best_squad = make_new_squad(args.budget, num_iterations, tag, gw_range, season)
UnboundLocalError: local variable 'make_new_squad' referenced before assignment`

**Comment by jack89roberts** [comment]
Thanks @ryanwilliams90 , this should now be fixed on the develop branch. So if you reinstall AIrsenal on that branch it should work as expected:
```
git checkout develop
git pull
pip install --upgrade --force-reinstall .
```
