### ISSUE TITLE
pip dependency changes November 2020

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#295]
I see this when installing AIrsenal:

```
ERROR: After October 2020 you may experience errors when installing or updating packages.
This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new
resolver before it becomes the default.
```

We should try `pip install --use-feature=2020-resolver .` as it suggests and see if there are any problems.

**Comment by Tdarnell** [comment]
I am planning on installing on a new machine this evening anyway (Ubuntu WSL), so will give this a go and report back.

**Comment by Tdarnell** [comment]
it installed correctly, but only when running pip3 via sudo due to a permissions error to site-packages...I can't remember if that was required before this update

pip version 20.2.4
python 3.6
Windows Subsystem for Linux Ubuntu 18.04.1 LTS

**Comment by jack89roberts** [comment]
Thanks, I think that's probably specific to the setup of your machine or it may be related to a few work in progress changes depending on which branch you installed from. But seems as though the pip changes won't be a problem so I'll close this one 🙂
