### ISSUE TITLE
Rename "sandbox" directory to "notebooks"

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#297]
To make the jupyter notebooks easier to find.

**Comment by gitrahulgit** [comment]
i want to work on it

**Comment by jack89roberts** [comment]
Hi @gitrahulgit - thanks for your interest in AIrsenal! This is already assigned and being worked on, but feel free to look through the other issues in the repo. We're always happy to receive new contributions!
