### ISSUE TITLE
Configurable DB location

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#324]
I guess a feature request more than a bug, is there a way to make the DB file location configurable? I believe currently its in /tmp/ location how can we change this so its created in a different location?

Also maybe even a DB configuration script if we want to use a database server so we can pass in the url (ip address) followed by DB name and Username and Password.

**Comment by jack89roberts** [comment]
Hi @RajeshTailor1 , the database location is set by `DB_CONNECTION_STRING` in `airsenal.framework.db_config.py`. You should be able to change it there (using any `sqlalchemy` compatible connection string), but you'll probably have to reinstall AIrsenal afterwards to get it to pick up the new location.

**Comment by nbarlowATI** [comment]
Hi, just to add to this - I think it should be configurable via an environment variable - looking in `db_config.py`, if you set the env var `AIrsenalDBFile` to the location you want, it should put the sqlite file there.
Or, if you want to use a postgres server instead, you can set the environment variable `AIrsenalDBUri` to point to the host.   However, this was tested with a postgres server in a docker container - trying more recently with an "Azure Database for PostgresSQL" database, I needed a username and password, and to remove the "check_same_thread=False" argument, so the line would be 
```
    DB_CONNECTION_STRING = "postgres://{}:{}@{}/airsenal".format(
        os.environ["AIrsenalDBUser"],
        os.environ["AIrsenalDBPassword"],
        os.environ["AIrsenalDBUri"]
    )
```
though I haven't tested this very much...

**Comment by RajeshTailor1** [comment]
Thanks for this I'll give this a test I have set the env var for AIrsenalDBFile to be the location I want, will update you on progress.

**Comment by RajeshTailor1** [comment]
Just an update really, so initially I just set the AIrsenalDBFile to a location for example /home/ubuntu/AIrsenal/ however this resulted in an error when running the initial DB setup script, then checking on the code it looks like the path had to include the file name too so after changing it to /home/ubuntu/AIrsenal/data.db the DB setup script ran without any issues.
