### ISSUE TITLE
Unable to access FPL team API even though it finds the ID

### ISSUE THREAD

**Issue by wknight** [alan-turing-institute/AIrsenal#329]
I get the following result at the end of running airsenal_setup_initial_db for the first time - because I only started on week 2. is there a way to get the script to move on if event/1/picks returns "not found"?

```
Getting selected players in squad 5877683 for first gameweek...
Unable to access FPL team API https://fantasy.premierleague.com/api/entry/5877683/event/1/picks/
Unable to access FPL team API https://fantasy.premierleague.com/api/entry/5877683/event/1/picks/
DONE!
```

**Comment by wknight** [comment]
Apologies everyone, just realized this was addressed in Issue [#257](https://github.com/alan-turing-institute/AIrsenal/issues/257)

**Comment by jack89roberts** [comment]
Great, yes if you reinstall the latest version it will work hopefully 🙂

**Comment by wknight** [comment]
Great! I need to change this line so that starting_gw = 2 though, right?

```
if NEXT_GAMEWEEK == 1:
        ### Season hasn't started yet - there won't be a team in the DB
        return True

    init_players = []
    starting_gw = 1
```

**Comment by jack89roberts** [comment]
It should work without you needing to change anything now, if you have a recent version of AIrsenal (downloaded and installed within the last month or so). Could you try `git pull` and then `pip install --force-reinstall .` from the parent `AIrsenal` directory and then see if you have the same problem after? If you do then this is a new bug.

**Comment by wknight** [comment]
I downloaded it yesterday, so I think it must be bug. 
It worked after I changed that line and did a `pip install --force-reinstall .`
However, it only found the first (actually second) gameweek. 
```
Getting selected players in squad 5877683 for first gameweek...
DONE!
```

**Comment by jack89roberts** [comment]
Ok I'll take a look after Christmas in that case. Were you having problems after (before making the change)? It might be that those messages are just printed for info and everything actually ran normally, not sure.

**Comment by wknight** [comment]
I had the problem above before making any changes. I just tried removing everything then reinstalling, and I get the same thing:
```
Getting selected players in squad 5877683 for first gameweek...
DONE!
```
And when i try running `airsenal_check_data` after that, I get the following error msg:
 ```
Traceback (most recent call last):
 File "/Users/willknight/anaconda3/envs/airsenalenv/bin/airsenal_check_data", line 5, in <module>
    from airsenal.scripts.data_sanity_checks import run_all_checks
  File "/Users/willknight/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/data_sanity_checks.py", line 1, in <module>
    from airsenal.framework.utils import (
ImportError: cannot import name 'get_teams_for_season' from 'airsenal.framework.utils' (/Users/willknight/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/utils.py)
```

**Comment by wknight** [comment]
I'm sorry, Jack. I don't think this is a bug after all. I got confused because the output only mentioned the first gameweek. 
I still get an error when I run `airsenal_check_data`, but both `airsenal_run_prediction` & `airsenal_make_squad` work.

**Comment by jack89roberts** [comment]
No probs, we should print something to make it clear what's happening in this case. Thanks for the `airsenal_check_data` error, that's probably something we've broken with changes elsewhere. I'll make a separate issue for that.
