### ISSUE TITLE
Cannot run predictions for weeks 2-7 of 2018/19 season

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#336]
Testing the `replay_season` functionality on the 2018/19 season gets off to a bad start...  We can run predictions (for 3 weeks ahead), starting from week 1, but for weeks 2-7, the player model fit fails to converge:
```
...
Error evaluating model log probability: Non-finite gradient.
Error evaluating model log probability: Non-finite gradient.

Optimization terminated with error: 
  Line search failed to achieve a sufficient decrease, no more progress can be made
```

It's not clear to me why this is - the player dataframes *appear* to be being filled correctly, and we don't see this issue for the 2019/20 or 2020/21 seasons.   
But we presumably *were* able to run predictions for those gameweeks at the time!

**Comment by jack89roberts** [comment]
Hmm, maybe this is linked to #303 and there's not enough data for the team model to converge (since 2017/18 is the first season in the database now I think, so just 1 season before 2018/19). But that doesn't explain why it works for week 1....
