### ISSUE TITLE
Not recognising team players

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#343]
I have a strange issue with my team (team id = 2585463)

After I run all the steps (lately I have had to rebuild the database on each run), the optimization is returning results where its advising me to transfer out players that I don't have in my team.

This started happening after I used my Free Hit card.  And now no matter how many times I rebuild the database and update the db its not returning the right results in the optimization, by right results I mean it's telling me to transfer out players I don't have in my team.  For example I ran the optimization today and it told me to transfer out Kane however I don't have Kane in my team.

Any advice?

**Comment by jack89roberts** [comment]
Hi @RajeshTailor1 , there was a bug fix for free hits (#312) that got merged to master around 3 weeks ago. Could you try pulling the latest version of the repo and reinstalling AIrsenal?

Also, you might see something similar if you forget to run `airsenal_update_db` after `airsenal_setup_initial_db` (if you're running them separately, `airsenal_run_pipeline` will do this for you by default if you're using that).

**Comment by RajeshTailor1** [comment]
I've recompiled everything and it all seems to work now, however I also noticed that the --bank switch has gone from the optimization script.  Does that mean its all coded in now?

**Comment by jack89roberts** [comment]
Great! Yes your money in the bank is calculated automatically now (in fact it was calculated automatically before too, whilst working on the optimisation code we realised the bank argument actually wasn't being used for anything).
