### ISSUE TITLE
Failed to get 2021 Attributes, Possible Mix up of Teams

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#374]
Hi, thanks for your hard work! I have a question... when running update_db, it is failing to get ATTRIBUTES 2021 for any player, are these to be added soon? Secondly, there is a bug I have found. Where it has team abbreviations (when predicting points)  some are mixed up. I think Burnley (BUR), Brighton (BHA) and Brentford are all getting mixed up. Either that or the fixtures are wrong. For example, it has Chris Wood playing first game against BUR(when it should be Brighton). And has Arsenal players first game against BHA (when it should be Brentford). Thanks!

_Originally posted by @sam-payne in https://github.com/alan-turing-institute/AIrsenal/issues/370#issuecomment-879350257_

**Comment by jack89roberts** [comment]
Hi @sam-payne , interesting! We've added some new data and have been fixing some things in the last few days/week, so it might be that you have a version of the code that isn't set up properly for the 2021/22 season. The new changes are on the `develop` branch. Could you try the following to reinstall and run again:

Delete the database:
- Mac/Linux: `rm /tmp/data.db`
- Windows: Delete `data.db` in the directory returned by  `python -c "from airsenal import TMPDIR; print(TMPDIR)"`.

Then, from the AIrsenal directory:
```
git checkout develop
git pull
pip install --force-reinstall -e .
```

And after that try running AIrsenal as normal (see the [readme](https://github.com/alan-turing-institute/AIrsenal/blob/master/README.md)).

For me the attributes for 2021/22 look ok with those changes (Chris Wood £7m BUR, Ivan Toney £6.5m BRE), so hopefully that will work for you too!

**Comment by sam-payne** [comment]
Hi @jack89roberts , many thanks. Checking-out the dev and rebuilding has fixed this.
