### ISSUE TITLE
airsenal_setup_initial_db - fails with value error message

### ISSUE THREAD

**Issue by kreshnaa-raam** [alan-turing-institute/AIrsenal#392]
when i try to run "airsenal_setup_initial_db"  command it fails with the value error message. i tried it with both main and develop branch. 

<img width="938" alt="Screenshot 2021-08-11 at 9 18 54 AM" src="https://user-images.githubusercontent.com/52041687/128966637-a4710b87-75c0-4ebd-aa5d-db678ab5801f.png">

**Comment by niall-anthony-mcnulty** [comment]
I have the same issue too

**Comment by jack89roberts** [comment]
Hi @kreshnaa-raam @niall-anthony-mcnulty - could you try deleting `/tmp/data.db` (by default, or if it's not there it should be at the path returned by `python -c "from airsenal.framework.db_config import DB_CONNECTION_STRING; print(DB_CONNECTION_STRING)"`), and then running the setup again?

I think this is what #380 will fix, I'll try to do that this week. Running `airsenal_setup_initial_db` will fail if an AIrsenal database already exists.
