### ISSUE TITLE
Look into player model (priors & unexpected results)

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#399]
Dumping some thoughts/values from something I was playing with re exploring why the player model may be over-valuing players like Firmino and Jesus.

Firmino:
- Empirical Bayes Estimate function returns: [17.20, 14.34, 82.46], corresponds to mean probabilities of [0.15, 0.13, 0.72]
- Modelled (mean posterior) probabilities are [0.25, 0.17, 0.58]

Prior (all forwards):
- Empirical Bayes Estimate function returns: alpha = [24.55, 12.04, 47.91], corresponds to mean probabilities of [0.29, 0.14, 0.57]
- Note Firmino score probability much closer to the prior than his empirical values.

Hypothesis:
- Prior too strong?
- Need to understand/read around the logic for using the empirical Bayes estimate above/how `get_empirical_bayes_estimates` is defined (essentially a weighted average of the number of goals, assists and neither across all forwards). I _think_ roughly speaking the way we currently treat the prior means the posterior is a combination of a player being on the pitch for 85 goals (24.55 + 12.04 + 47.91) with their involvement at the all-forwards average, plus however many goals they have actually been on the pitch for (and how many they scored/assisted). This maybe means the prior has a weighting equivalent ~a full season for a top team (who might score 80 goals a season), or as several seasons for a lower team.
- I think we should use smaller alpha values in the Dirichlet prior, but need to test this properly.
   - Quick test scaling down the prior:
      - sum(alpha) = 10 gives Firmino posterior mean of  [0.23, 0.18, 0.59] 
      - sum(alpha) = 1 gives Firmino posterior mean of  [0.22, 0.18, 0.59]
      - These are both still higher than the empirical values, so maybe barking up the wrong tree. It also screws up other players with few appearances who can get crazy high score probabilities etc. with a too weak prior. Fitting the model also seems to get really slow if the prior is weak.
      - Worth cross-checking with the Stan model to compare.
- This may also explain why AIrsenal sometimes likes defensive midfielders from top teams more than expected (if they're benefitting from the all-midfielder-average prior)?

Figure:
- Top: Distribution of player means probabilities from empirical bayes estimates.
- Middle: Samples from the prior used for all forwards
- Bottom: Distribution of mean player probabilities in the model posterior.

![download](https://user-images.githubusercontent.com/16308271/129274583-5f00f1de-7b65-429d-a69e-951d165712fb.png)

**Comment by jack89roberts** [comment]
It's dawned on me that we have a conjugate prior model so we should be able to compute the posterior exactly:

```
Prior: (prob_score, prob_assist, prob_neither) ~ Dirichlet(a_score, a_assist, a_neither)
# where the a values are currently average goals for all players in that position

Posterior:  (prob_score, prob_assist, prob_neither) ~ Dirichlet(a_score + n_score, a_assist + n_assist, a_neither + n_neither)
# where the n values are the goals scored etc. by the player (weighted for fraction of minutes played)
```

**Comment by jack89roberts** [comment]
For Firmino the exact posterior mean _should_ be:
- With the current prior: [0.21, 0.13, 0.66]
- With prior sum(alpha) = 10:  [0.16, 0.13, 0.71]
- With prior sum(alpha) = 1: [0.15, 0.13, 0.72]

Unsure how to go about finding a suitable prior, but perhaps having it as the equivalent of around 10 matches of data would be sensible. Last season teams scored ~1.3 goals per match on average, so that would correspond to sum(alpha) ~= 13.

**Comment by nbarlowATI** [comment]
Ah, excellent work, and very interesting @jack89roberts !!
Yet another case where replay season would be useful to tune the best value (wouldn't even need optimization - just comparing predictions to actual scores/assists), but yeah, scaling down sum(alpha) to something like 13 as you suggest seems reasonable...

Do the big spikes at particular values in the posterior plots above correspond to players that didn't play in previous seasons?

**Comment by jack89roberts** [comment]
I think you're probably right about the spikes on the bottom row @nbarlowATI , nice spot! Can see they line up with the mean of the prior in the middle row, which is what you'd expect new players to get. Removing them would probably be better to compare properly.

**Comment by jack89roberts** [comment]
There's an implementation of the conjugate model in #414 now, which is a fancy way of saying I've implemented adding two numbers together 😀 

It does confirm there are cases where the numpyro model (and possibly the stan model before too, haven't checked) give unexpected results, e.g. it gives much higher goal-scoring probabilities to Firmino and Joelinton than the conjugate model even when using similar priors - 25% vs. 19% for Firmino and 28% vs. 20% for Joelinton. And with the weaker prior I'm proposing (though it may be _too_ weak) these would be further reduced to 16% and 14% in the conjugate model.

The conjugate model is faster and should be more robust and stable, so there shouldn't be any downside to using it. But if we wanted to improve the player model we'd need to go back to numpyro so I'd like to understand what's going on with it.

There's a [notebook here](https://github.com/alan-turing-institute/AIrsenal/blob/399-player-model-priors/notebooks/conjugate_player_model.ipynb) with some thoughts and playing around. Would be good to discuss everything properly in the next hack session.
