### ISSUE TITLE
A league for people running the software?

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#402]
Not a bug or feature, but potential bit of fun. Is there a league set up for people running the software? Should theoretically be a very close league

**Comment by nbarlowATI** [comment]
Hi @mildfuzz  - great idea - thanks!!
Just created a mini-league: "Prem-AI League".    
The code to join is: **3rn929**
We will add this info to the README.md

Hopefully see your team there! :)

**Comment by Tdarnell** [comment]
I've joined with "Machine Learn-Ings" :D

**Comment by RajeshTailor1** [comment]
I've joined too with "Mayans MC"
