### ISSUE TITLE
More players in DB than API 

### ISSUE THREAD

**Issue by cgmorale** [alan-turing-institute/AIrsenal#415]
When I run the optimization command I keep getting this error: 
"RuntimeError: Something strange has happened - more players in DB than API" 
Is there an easy way to fix this?

**Comment by nbarlowATI** [comment]
Hi @cgmorale,  probably the safest thing to do is to remove your database sqlite file (which by default will be `/tmp/data.db' on Linux or Mac, or on Windows it will be somewhere defined by `tempfile.gettempdir()` and rerun the full pipeline, either with the command 
`airsenal_run_pipeline` or doing the steps individually (`airsenal_setup_initial_db`, `airsenal_update_db`, `airsenal_run_prediction`, `airsenal_run_optimization`).  (note that for each of these, you can see the list of command line options with `--help`).

Hope this helps!
