### ISSUE TITLE
Ensure consistent argument names across airsenal functions

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#457]
E.g. gameweek vs. gw in these two:

```
airsenal_run_prediction --season 1920 --gameweek_start 1 --gameweek_end 4
airsenal_run_optimization --season 1920 --gw_start 2 --gw_end 3
```

**Comment by chahak13** [comment]
Hi. I was checking the issues and this seems related to #382? What are your opinions about it? I was thinking about starting to work on this if no one else has.

**Comment by jack89roberts** [comment]
Sorry for the delay in getting back to you @chahak13 ,  but sure feel free to work on this and/or #382 . #382 is a bigger change so we'd need to make sure all the maintainers are happy with the proposed new interface (when you get to creating it/proposing something).

**Comment by chahak13** [comment]
Okay! I understand, yeah. I'll try to fix this first while creating a proposal on the side if possible. Thanks!
