### ISSUE TITLE
airsenal_run_prediction not returning any text

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#460]
Running
```bash
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218"  airsenal airsenal_run_prediction --weeks_ahead 3
```

Returns nothing, just calmly exits after a couple of seconds

**Comment by mildfuzz** [comment]
Running on ubuntu:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by jack89roberts** [comment]
Does
```
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218"  airsenal airsenal_run_pipeline --weeks_ahead 3
```
also return nothing @mildfuzz (run pipeline rather than run prediction)?

**Comment by mildfuzz** [comment]
yes. pipeline also returns nothing

**Comment by jack89roberts** [comment]
Hmm weird, and you don't see anything printed at all? How about if you open bash in the container and run it there?
```
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218" airsenal bash
airsenal_run_pipeline --weeks_ahead 3
```

**Comment by mildfuzz** [comment]
root@f34f5c129e2e:/airsenal# airsenal_run_pipeline --weeks_ahead 3
Illegal instruction (core dumped)

**Comment by mildfuzz** [comment]
I tried purging all the images and volumes and starting again, same result

**Comment by jack89roberts** [comment]
I'm not really sure where to start with this one, to be honest. searching around it could be something specific about the hardware you're running on. Are you running on a new system, by any chance (because you've had AIrsenal working before, right?) Or is it possible you're running out of memory in the container (unlikely I think)?

Ultimately we can also try to pinpoint whether this is coming from a specific python package/command, e.g. if you connect to the container again

```
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218" airsenal bash
```

Then see if these imports work as a starting point:

```
python
>>> import numpy
>>> import numpyro
>>> import pygmo
>>> import airsenal
>>> from airsenal.framework.utils import *
```

**Comment by mildfuzz** [comment]
They all seem to exit correctly apart from `numpyro`

```
import numpyro
Illegal instruction (core dumped)
```

**Comment by jack89roberts** [comment]
I forgot to reply to this but it looks like some nasty incompatibility between your hardware/OS, Docker (/the OS in the container), and Numpyro. We may need to open an issue with them but I'd like to see if we can reproduce it on another system first.

**Comment by jack89roberts** [comment]
Hi @mildfuzz , could you send us some more specs of the hardware you're running on when getting this error? Particularly which CPU if possible.
