### ISSUE TITLE
Seeing login error in optimisation

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#475]
```
Error loging in:
<html>
<head>
<title>premierleague.com</title>
<style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style>
</head>
<body style="margin:0">
<p id="cmsg">Please enable JS and disable any ad blocker</p>
<script>
var dd={\'cid\':\'AHrlqAAAAAMANBwtYFjIwQsAVoYLnQ==\',\'hsh\':\'5DE3E6A7D87D0E4E8979F7A1C7BD73\',\'t\':\'bv\',\'r\':\'b\',\'s\':37187,\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js">
</script>
</body>
</html>\n'
```

Maybe something about authentication for the API has changed?

**Comment by AlexLightning** [comment]
Any news regarding this?

**Comment by jack89roberts** [comment]
No I've not had a chance to investigate yet, have you seen it as well/has it caused you problems @AlexLightning ?

**Comment by AlexLightning** [comment]
Yes, it happens to me too. And for some reason is not getting my team right... When I run optimization it recommends me to get out players I don't have at all...

**Comment by AlexLightning** [comment]
While trying to get screenshot of examples, I noticed it worked. I suspect it might have been because I kept having an error with updating the database and I only ran the init db command with re-running the update db command. I've opened another issue for that one, thanks for the quick reply.
