### ISSUE TITLE
[FIX] Can't run on M1 macs with/without conda 

### ISSUE THREAD

**Issue by subash774** [alan-turing-institute/AIrsenal#491]
I was having problems with conda even with the suggested miniconda fix so I ventured into making this work on M1 macs without requiring conda.

This was done by upgrading the version of numpyro used in https://github.com/anguswilliams91/bpl-next.git (forked and modified requirements to use forked version instead). 
@jack89roberts as all tests are passing ([my fork](https://github.com/subash774/AIrsenal)), we should probably try upgrade numpyro version? If not then I am happy to maintain "M1 branch" until we figure out concrete solution. 

It's functional with vanilla `pip` but of course using some form of virtual environment is recommended, I used `virtualenv` for my testing.

Steps to follow:
``` 
git clone https://github.com/subash774/AIrsenal.git
```

```
cd AIrsenal
```

```
pip3 install virtualenv
```

```
virtualenv venv
```

```
source venv/bin/activate
```

```
echo ______YOUR_FPL_TEAM_ID_HERE_________ > airsenal/data/FPL_TEAM_ID
```

```
pip install .
```

Then follow instructions as usual listed here: https://github.com/alan-turing-institute/AIrsenal#1-creating-the-database

**Comment by jack89roberts** [comment]
Oh cool, thanks @subash774 ! Could you do the following:

- Try installing and running AIrsenal from the `develop` branch (see this work in progress PR: https://github.com/alan-turing-institute/AIrsenal/pull/490). We're in the process of moving to Poetry for managing most dependencies - does AIrsenal work for you on that branch already? (that branch also has the changes/data updates you'll need to get AIrsenal working for the new season)

- If the `develop` branch doesn't work for you, could you make pull requests here (building on top of `develop`) and to the `bpl-next` repos (wherever's appropriate/needed?)

Happy to help with any of the above anything's not clear.

**Comment by subash774** [comment]
Hey,
On my fork, I've merged from develop to main already and all is working 👍

**Comment by subash774** [comment]
How should we proceed then? A separate branch for M1 users or upgrade numpyro for all users (I haven't tested with docker and conda variations)? What do you think?

**Comment by subash774** [comment]
The only changes required were for `requirements.txt` file, nothing else was changed. However, in the requirements, I've pointed to my own fork of https://github.com/anguswilliams91/bpl-next.git, I can raise an issue / PR to upgrade `numpyro` there but as it's not been updated since April 2021, I say it's safe to assume, using my fork is safe for now, we can point it back to theirs once it's updated with the version we need.

In terms of submitting PR, I've already merged develop to main on my main branch, if that creates a big merge conflict for you to resolve, I will revert and push just the requirements file that was changed 👍

**Comment by jack89roberts** [comment]
Ah right, could you make a PR to bpl-next then? We didn't create it but do have maintainer rights over there too. And once that is merged we can update the AIrsenal reqs.

**Comment by subash774** [comment]
Are we the only ones using it? Worried that upgrading `numpyro` there might break other usages if it's not backward compatible.

**Comment by jack89roberts** [comment]
@subash774 could you try installing AIrsenal from `main` (after pulling the latest changes) and check that it works for you now?

Re backwards compatibility, we may be the only ones using `bpl-next` as it's a more recent/work-in-progress replacement for the original `bpl`. AIrsenal itself has multiple users. But we haven't made breaking changes to the APIs (in this case) and people can install old versions of either package if needed.

**Comment by subash774** [comment]
@jack89roberts perfect! LGTM 👍 Nice work :) 

Something to keep in mind however, running `airsenal_run_pipeline --weeks_ahead 3` will produce `ModuleNotFoundError: No module named 'pygmo'` error. Not sure if this is because the season hasn't started yet and pipeline uses  `airsenal_run_optimization` instead of `airsenal_make_squad`?
