### ISSUE TITLE
FPL team ID missing

### ISSUE THREAD

**Issue by subash774** [alan-turing-institute/AIrsenal#504]
@jack89roberts recent merge seems to have broken the reading of `FPL_TEAM_ID` file?
Tested on MacOS and Linux, same error of:
```
Getting initially selected players in squad MISSING_ID for first gameweek...
Unable to access FPL team API https://fantasy.premierleague.com/api/entry/MISSING_ID/event/1/picks/
Unable to access FPL team API https://fantasy.premierleague.com/api/entry/MISSING_ID/event/2/picks/
```

**Comment by subash774** [comment]
FIX: 
Fixed it with `export FPL_TEAM_ID=______`
But getting the log below for some reason 🤔
```
Running optimization with fpl_team_id 1634671
Getting starting squad for 1634671
No existing squad or transfers found for team_id 1634671
Will suggest a new starting squad:```

**Comment by jack89roberts** [comment]
Hmm this sounds like another form of #501 , I'll try to dig into it ASAP but probably won't be until later in the week.

**Comment by subash774** [comment]
From my testing, error above only occurs when running without logging in and running individual steps rather than pipeline, hope that helps narrow things down 👍 exporting the team id and running the pipeline is a quick fix for now

**Comment by jack89roberts** [comment]
Those of you with this problem may like to try installing AIrsenal from the latest develop branch:

```
git checkout develop
git pull
pip install .
```

noting the [new instructions in the readme](https://github.com/alan-turing-institute/AIrsenal/blob/develop/README.md#configuration) for setting the team ID and other settings with the new `airsenal_env` command.
