### ISSUE TITLE
Wrong team after wild card

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#508]
I have played my wild card, but during the pipeline the API failed, so I performed the wildcard manually 

Now the make_squad method returns my old players

**Comment by jack89roberts** [comment]
Would you mind sharing your team ID? Then I can try to recreate (and fix) it.

**Comment by mildfuzz** [comment]
5165238

**Comment by nbarlowATI** [comment]
Hi @mildfuzz, are you supplying your FPL username and password (either by typing them in at the prompt or having FPL_LOGIN and FPL_PASSWORD files in your `data/` directory?    I think that if you don't login, then the data fetcher will only have access to the set of transfers you made once the next gameweek starts (when everyone can see your team).

If you are logged in, then I would think it should be able to see your real current squad.   If you're happy to do a bit of debugging, then I'd suggest putting some `print` statements in the function `get_starting_squad` in the file `airsenal/framework/optimization_utils.py` - in particular to see if the code block under `if use_api` is being called...
(Note that you need to `pip install .` after changing the code in order to use the changes...)

**Comment by mildfuzz** [comment]
tried that. I've noticed it's telling me to field players I have never had

I have an active wildcard, could that be screwing with it?

**Comment by mildfuzz** [comment]
I'll try to find 5 mins to to stick some logs in

**Comment by mildfuzz** [comment]
```
====================================

Strategy for Team ID: 5165238
Baseline score: 189.01851729922828
Best score: 190.35490020751956
 ===============================================
 ========= Optimum strategy ====================
 ===============================================

 =========== Gameweek 4 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Matheus Luiz Nunes			Jefferson Lerma Solís

 =========== Gameweek 5 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Lewis Dunk			William Saliba

 =========== Gameweek 6 ================

Chips played:  wildcard

Players in:			Players out:
-----------			------------
Hugo Lloris			Illan Meslier
Dean Henderson			Reece James
Kieran Trippier			Kyle Walker
Trent Alexander-Arnold		Kevin De Bruyne
Fabian Schär			Kieffer Moore
Jefferson Lerma Solís		Erling Håland
Luis Díaz			José Malheiro de Sá
Pedro Lomba Neto			Josh Dasilva
Harry Kane			Matheus Luiz Nunes
Ivan Toney			Lewis Dunk

==========================
 Total score: 190

Getting starting squad for 5165238

=== starting 11 ===


== GK ==

Alisson Ramses Becker (LIV)

== DEF ==

Jonathan Castro Otto (WOL)
Trent Alexander-Arnold (LIV)(VC)
Aaron Cresswell (WHU)
Andrew Robertson (LIV)

== MID ==

Bruno Guimarães Rodriguez Moura (NEW)
Kevin De Bruyne (MCI)(C)
Phil Foden (MCI)

== FWD ==

Harry Kane (TOT)
Bryan Mbeumo (BRE)
Danny Welbeck (BHA)

=== subs ===

David Raya Martin (BRE)
César Azpilicueta (CHE)
Anthony Elanga (MUN)
```
look here, it tells me to swap in Harry Kane in week 6, but has him in my starting 11 for this week.

**Comment by mildfuzz** [comment]
Erling Håland, who it's telling me to swap out, it would only know if it had access to my team as I added him as part of the wildcard this week, so not in my public team yet

**Comment by nbarlowATI** [comment]
Hmmm... this is very odd....    If you have a few mins, could you try the following? 
```
python
>>> from airsenal.framework.utils import *
# verify that we have FPL_TEAM_ID, FPL_LOGIN, FPL_PASSWORD set:
>>> fetcher.FPL_TEAM_ID
>>> fetcher.FPL_LOGIN
>>> fetcher.FPL_PASSWORD
# If these look right to you, next step is to get the current squad as the API sees it:
>>> squad = fetcher.get_current_squad_data(fetcher.FPL_TEAM_ID)
>>> for pick in squad['picks']:
>>>    print(get_player_from_api_id(pick['element_id']))
```
and see if this looks like your current squad?    AFAIK, this is exactly the info that the FPL website is using to get your squad view, so I'd be very surprised if it's wrong, but we should check before moving the investigation to next stage.....

**Comment by mildfuzz** [comment]
had to change `element_id` to `element`, but yeah, spits out the correct team.

```
José Malheiro de Sá
Reece James
Kyle Walker
William Saliba
Emerson Leite de Souza Junior
Mohamed Salah
Marcus Rashford
Kevin De Bruyne
Josh Dasilva
Danny Welbeck
Erling Haaland
Illan Meslier
Kieffer Moore
Jefferson Lerma Solís
Jonathan Castro Otto
```

but then I run make_squad and it includes players I do not have

```
╰─❯ airsenal_make_squad --num_gameweeks 3
---------------------
Optimised total score (gameweeks 4 to 6): 193.23
Expected points for gameweek 4: 69.45
---------------------

=== starting 11 ===


== GK ==

Hugo Lloris (TOT) <--- NOPE

== DEF ==

Ben Davies (TOT) <--- NOPE
Kyle Walker (MCI)
William Saliba (ARS)
Reece James (CHE)

== MID ==

Mohamed Salah (LIV)(C)
Phil Foden (MCI) <--- NOPE
Marcus Rashford (MUN)
Luis Díaz (LIV) <--- NOPE

== FWD ==

Danny Welbeck (BHA)
Erling Haaland (MCI)(VC)

=== subs ===

Rayan Aït-Nouri (WOL) <--- NOPE
Pedro Lomba Neto (WOL) <--- NOPE
Robert Sánchez (BHA) <--- NOPE
Kieffer Moore (BOU) <--- NOPE
```

**Comment by nbarlowATI** [comment]
Ah, I think `airsenal_make_squad` is not the script you want to be running mid-season... This is the one for creating an squad from scratch.
`airsenal_run_optimization` is the one that should look at your existing team and make changes.
We should clarify this in the documentation - I see that it says you can use `airsenal_make_squad` for wildcards, but the preferred way of doing that would be 
`airsenal_run_optimization --wildcard_week [gameweek]`.
