### ISSUE TITLE
Add number of previous seasons as an argument to `airsenal_setup_initial_db`

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#513]
At the command-line, which to implement will mean all these functions should take a `seasons` argument (list of seasons to include):

https://github.com/alan-turing-institute/AIrsenal/blob/e9df380903f51c037e72680639140e306d8a7a75/airsenal/scripts/fill_db_init.py#L26-L35

Then in main add an argparse argument `n_previous` or similar that defaults to 3, with the values of the seasons list computed with `airsenal.framework.utils.get_past_seasons(n_previous)`

This will help for replaying seasons, in particular.

**Comment by rchan26** [comment]
I've made some progress for this in the (prev_seasons_arg)[https://github.com/alan-turing-institute/AIrsenal/tree/prev_seasons_arg] branch. But this fails for when `CURRENT_SEASON` is not included.
