### ISSUE TITLE
Account for 5-subs rule change in data checks

### ISSUE THREAD

**Issue by rchan26** [alan-turing-institute/AIrsenal#525]
When running sanity data checks using `airsenal_check_data`, it will raise errors for 22/23 season when "Checking 11 to 14 players play per team in each fixture...". Since 22/23, 5 subs are allowed. To fix this, need to make changes to `fixture_num_players` function in [data_sanity_checks.py](https://github.com/alan-turing-institute/AIrsenal/blob/main/airsenal/scripts/data_sanity_checks.py) to account for this rule change.

Also add some lines into the notes of this function to note that 5-subs allowed from 22/23:

https://github.com/alan-turing-institute/AIrsenal/blob/main/airsenal/scripts/data_sanity_checks.py#L96-L106

**Comment by jack89roberts** [comment]
There's some logic for the 19/20 season for this that we can update for all seasons from 22/23 (note it also fails for concussion subs, which is more difficult to account for):

https://github.com/alan-turing-institute/AIrsenal/blob/ed9dec23451e06d27f7ebad2fcba3d501e8b04b1/airsenal/scripts/data_sanity_checks.py#L173-L177

**Comment by rchan26** [comment]
I've just made a quick fix for this on the [develop](https://github.com/alan-turing-institute/AIrsenal/tree/develop) branch. Still have concussion subs to figure out...

**Comment by jack89roberts** [comment]
We'd need extra data from somewhere to do concussion subs so don't worry about that 🙂
