### ISSUE TITLE
Error executing airsenal_make_transfers Error 403

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#534]
Hi Team - I am attempting to execute the airsenal_make_transfers command and I receive the following error:

Error loging in: b'<html><head><title>premierleague.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'cid\':\'AHrlqAAAAAMAu-24bHqZ0PgAA4WeIw==\',\'hsh\':\'5DE3E6A7D87D0E4E8979F7A1C7BD73\',\'t\':\'fe\',\'r\':\'b\',\'s\':37449,\'e\':\'4f81e411cd66e7e04653964c0d3d495bf1f22c87e3265f16fb04a5ba7eabb554\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n'
Transfers unsuccessful due to unknown error
Response status code: 403
Response text: {"detail":"Authentication credentials were not provided."}
fpl_team_id is None
Got fetcher 3764595
Error loging in: b'<html><head><title>premierleague.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'cid\':\'AHrlqAAAAAMAeXVm1tpsvMkAA4WeIw==\',\'hsh\':\'5DE3E6A7D87D0E4E8979F7A1C7BD73\',\'t\':\'fe\',\'r\':\'b\',\'s\':37449,\'e\':\'70515df0e33955addcb00f3babe3fab57d5ebe1b45feab7e206f67770c1f1005\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n'
Unable to access FPL API
Got picks None
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/airsenal_make_transfers", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airsenal/scripts/make_transfers.py", line 328, in main
    set_lineup(args.fpl_team_id)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airsenal/scripts/set_lineup.py", line 100, in set_lineup
    squad = get_lineup_from_payload(picks)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airsenal/scripts/set_lineup.py", line 70, in get_lineup_from_payload
    for p in lineup["picks"]:
TypeError: 'NoneType' object is not subscriptable

Any ideas on how to resolve this? I have ensured the email and password are stored in environment variables but I noticed you mention to store them in files will that make a difference?

**Comment by nbarlowATI** [comment]
Hi @RajeshTailor1  - ohhh, this looks very similar to #523  :( 
I hope FPL isn't starting to add captchas to more and more things to try and prevent logins from code.   
As described in a comment on that issue, it should still be possible to run most of the AIrsenal pipeline (including optimization) without logging in.   However, I think that `airsenal_make_transfers` is probably the main part that would absolutely require being logged-in, so if FPL put a captcha in, I'm afraid that would block us...

**Comment by RajeshTailor1** [comment]
This makes sense I understand why I am getting this error now.  We can close this issue.
