### ISSUE TITLE
FPL_TEAM_ID not set correctly

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#536]
Hi Team,

So I have done a brand new fresh install and everything went smoothly however on executing the command for creating the database I get the following error:

Unable to access FPL API
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/airsenal_setup_initial_db", line 5, in <module>
    from airsenal.scripts.fill_db_init import main
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airsenal/scripts/fill_db_init.py", line 5, in <module>
    from airsenal.framework.transaction_utils import fill_initial_squad
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airsenal/framework/transaction_utils.py", line 9, in <module>
    from airsenal.framework.utils import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airsenal/framework/utils.py", line 153, in <module>
    NEXT_GAMEWEEK = get_next_gameweek()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airsenal/framework/utils.py", line 89, in get_next_gameweek
    if len(fixture_data) == 0:
TypeError: object of type 'NoneType' has no len()

Any ideas on what could cause this? I have double checked the FPL_TEAM_ID and its set correctly

**Comment by jack89roberts** [comment]
Hi @RajeshTailor1 , have you tried another run in case it was a problem with the FPL API at the time (rebuilding a clean database, e.g. with `airsenal_run_pipeline --clean`)? It looks like you didn't get any fixture data back. And does it make a difference if you set `FPL_LOGIN` and `FPL_PASSWORD` (if you haven't already)?

**Comment by RajeshTailor1** [comment]
Ok so it seems like it’s working now I have no idea what resolved it.  However I seem to have a follow up issue which I could raise a new issue but just putting it here:

when running the commands to add the FPL TEAM ID in the airsenal env it doesn’t update I can still see my old team Id from last season I also tried deleting but it won’t delete but thankfully I can pass in my new team id with parameters so I can temporarily resolve it.

**Comment by jack89roberts** [comment]
Hmm, weird. o Can you try:

Getting the value of AIRSENAL_HOME from:

```
airsenal_env get
```

Check the current value of the FPL_TEAM_ID in the saved file:

```
cat '<AIRSENAL_HOME>/FPL_TEAM_ID`
```

This should match the value of FPL_TEAM_ID returned from `airsenal_env get`  above.

Try to set a new team ID:

```
airsenal_env set -k FPL_TEAM_ID -v 123456
```

Verify the value has changed in the file:

```
cat '<AIRSENAL_HOME>/FPL_TEAM_ID`
```

Verify the value has changed in the AIrsenal command:

```
airsenal_env get -k FPL_TEAM_ID
```

**Comment by RajeshTailor1** [comment]
OK so the command 

cat '<AIRSENAL_HOME>/FPL_TEAM_ID` - returns the correct TEAM ID

airsenal_env set -k FPL_TEAM_ID -v 123456 - This command executes without any errors.

However when running airsenal_env get -k FPL_TEAM_ID it returns the old team id.  And also when running airsenal_env get shows the old team id (still).

**Comment by jack89roberts** [comment]
Weird, and presumably `cat '<AIRSENAL_HOME>/FPL_TEAM_ID'` is still returning the old ID after you try to set it to 123456?

Could you check what's in your AIRSENAL_HOME directory and the permissions you have on the files in it? 

```
ls -la "<AIRSENAL_HOME>"
```

And verify you don't have a `FPL_TEAM_ID` environment variable set. In a python shell:

```
import os
"FPL_TEAM_ID" in os.environ
```

should be False.

**Comment by RajeshTailor1** [comment]
ok so looks like I had the old team id set as an environment variable!! I have resolved this now and its all working as expected.  I'll go ahead and close this too.  :)
