### ISSUE TITLE
Recommended Transfers don't align with the Team Starting 11

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#542]
Hi Team,

I am getting some strange results when running the optimizations.  As you can see below the recommended transfers for this coming gameweek don't align with the starting 11 for the current gameweek.  It's asking me to transfer in Castagne however he doesn't seem to appear in the squad.  In fact the squad displayed is completely different to my current team.  Now I can only think on 1 reason its because I used a wildcard last week does this mean I have to rebuild the DB? I did run the update DB command.

```
====================================

Strategy for Team ID: xxxxxxxx
Baseline score: 163.0439408577813
Best score: 168.31249637285867
 ===============================================
 ========= Optimum strategy ====================
 ===============================================

 =========== Gameweek 11 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Timothy Castagne			Thiago Emiliano da Silva

 =========== Gameweek 12 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Virgil van Dijk			Kieran Trippier

 =========== Gameweek 13 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Gabriel Martinelli Silva		Leandro Trossard

==========================
 Total score: 168 

Getting starting squad for xxxxxxxx

=== starting 11 ===


== GK ==

Illan Meslier (LEE)

== DEF ==

Ben Chilwell (CHE)
Romain Perraud (SOU)
Lewis Dunk (BHA)

== MID ==

Jordan Ayew (CRY)
Bruno Borges Fernandes (MUN)(C)
Son Heung-min (TOT)
Harvey Barnes (LEI)(VC)
Pascal Groß (BHA)

== FWD ==

Gabriel Fernando de Jesus (ARS)
Ivan Toney (BRE)

=== subs ===

Michail Antonio (WHU)
Issa Diop (WHU)
Sam Johnstone (CRY)
Trent Alexander-Arnold (LIV)
```

**Comment by jack89roberts** [comment]
At a guess, this may be linked to your other issue (#536). But could you try pulling the latest version of AIrsenanl from the repo, reinstalling, and then doing a clean run (`airsenal_run_pipeline --clean`) to see if anything changes?

**Comment by RajeshTailor1** [comment]
You are correct looks like the teamids mismatch is causing several issues.  However I have managed to clean up the teamids (I'll explain in the other post), by cleaning up the teamids and re-installing from the repo has resolved this issue for me.  I'll close this thanks.
