### ISSUE TITLE
Where to ask more general questions not related to development

### ISSUE THREAD

**Issue by markjam** [alan-turing-institute/AIrsenal#560]
I have been very reticent to post here given I am not a developer and know not quite enough to get by. Have been using v1.5.1 since earlier in season. Where might I find some instructions on how to upgrade from 1.5.1 to 1.5.2. I have been flailing around without success doing much reading on Conda, git etc... This is helping me build/re-familiarise myself with Linux etc... I'm not quite sure how to label this posting correctly. Is there somewhere better for newbies to discuss & not clog up this workspace.

Mark J

**Comment by markjam** [comment]
I decided to conda remove the environment and rm -rf the AIrsenal dir and start again which worked fine. Sorry to clutter this board unnecessarily.

**Comment by rchan26** [comment]
hey @markjam - sorry for the late response, we've all been taking a break over Christmas!

glad to see that you've got it working again, and no need to be sorry! if you any more questions about getting it to work in the future, this would absolutely be the place to post any questions, and we'll be happy to help then too! 😄
