### ISSUE TITLE
2023-2024 season

### ISSUE THREAD

**Issue by sahildaswani** [alan-turing-institute/AIrsenal#598]
Will this be updated for the 2023 to 2024 season?

**Comment by jack89roberts** [comment]
Hi @sahildaswani , yes, definitely! I'll try to get it sorted in the next few days, there are only a couple of things that need doing I think.

**Comment by jack89roberts** [comment]
This is now done @sahildaswani

**Comment by tshrjn** [comment]
Hi, is there a mini league planned for this season?

**Comment by jack89roberts** [comment]
@tshrjn Yes, the code to join is `uke1z3` (I've updated the readme to include that) 🙂
