### ISSUE TITLE
Issues running replay_season

### ISSUE THREAD

**Issue by updega2** [alan-turing-institute/AIrsenal#604]
It's possible I'm setting it up and running wrong, but has anyone had any success using the airsenal_replay_season? I keep running into different issues, most of which seem to stem around "NEXT_GAMEWEEK" and not being updated. I think I've fixed a couple of the issues, but I keep running into more. 

Are there known issues? Has anyone had success using it?

Thanks!

**Comment by jack89roberts** [comment]
Hi @updega2 Thanks for posting the issue, I just tried running it and it failed. I'll try to investigate why asap.

**Comment by jack89roberts** [comment]
@updega2 if you try installing from this branch it should work for you hopefully: https://github.com/alan-turing-institute/AIrsenal/pull/605 but I need to understand when/where the bug appeared, it was fine a few weeks ago.

**Comment by updega2** [comment]
Ah I see, thanks for looking into it. I'll try that out. Thanks!
