### ISSUE TITLE
FileNotFoundError: No such file or directory: '/home/user/.local/lib/python3.8/site-packages/airsenal/scripts/../data/teams_2324.csv'

### ISSUE THREAD

**Issue by exenrnov** [alan-turing-institute/AIrsenal#607]
Hi,

bit frustrated. Tried to get this going a few weeks back but gave up since I saw there was no teams_2324. Came back today to try again and I get FileNotFoundError:  No such file or directory: '/home/enrique/.local/lib/python3.8/site-packages/airsenal/scripts/../data/teams_2324.csv' when running airsenal_setup_initial_db.

I am running on a windows PC but with conda. command do work (i.e airsenal_env get returns correct values inluding: DB_CONNECTION_STRING: sqlite:////home/user/.local/share/airsenal/data.db)

When i check the directory the teams_2324.csv is not there. there are teams_1516 all the way to teams_2223. I have a suspicion it has to do with me installing it without conda first. Then with conda but the 2324 csv was not added untill 2 weaks ago (after I installed).

Have pulled newest version. Tried to remove conda enviroment and reactivated it. Tryid pulling again in a different place to see if it would help but still get the same problem.

How do I update the /.local/lib/python3.8/site-packages/airsenal/scripts/../data/ to have the correct files?

**Comment by jack89roberts** [comment]
Hi @exenrnov sorry for the frustration.

Remove any AIrsenal installations/related files:

```
pip uninstall airsenal
rm -rf /home/enrique/.local/lib/python3.8/site-packages/airsenal
rm -rf /.local/lib/python3.8/site-packages/airsenal
conda remove -n airsenalenv --all
```

Then, if you still have a version of the repo cloned (if not follow the instructions from the readme), do the following from the parent `AIrsenal` directory:

```
git pull
git checkout develop
conda env create
conda activate airsenalenv
```

If you would like to be able to quickly update to newer versions in the future you can run this (making sure the conda environment is activated):

```
pip install -e .
```

Then just running `git pull` in future from the `AIrsenal` directory should be enough to get you the latest version of AIrsenal running.

Finally (still with the conda environment activated), try:

```
airsenal_run_pipeline --clean
```

I hope that will get you a clean and working version of AIrsenal but if not let us know and we'll continue to debug it.

**Comment by exenrnov** [comment]
Thanks for reply.

I have followed instruction. Now instead I am getting:

":~/AIrsenal$ airsenal_run_pipeline
Traceback (most recent call last):
  File "/home/enrique/.local/bin/airsenal_run_pipeline", line 5, in <module>
    from airsenal.scripts.airsenal_run_pipeline import run_pipeline
ModuleNotFoundError: No module named 'airsenal'"

Where before airsenal_env get worked it no longer does. So confused. Did try installing docker, but since I have never used that I gave up after a few hours.

Thanks for any help.

**Comment by exenrnov** [comment]
I took my work MAC and got it running there. Not sure if this problem is needed anymore.

**Comment by jack89roberts** [comment]
Ah ok you also would have needed to delete any files starting `airsenal` in `/home/enrique/.local/bin/` before reinstalling. But there might be an issue with conda on that laptop - after running `conda activate airsenalenv`, `which python` and `which airsenal_run_pipeline` should return paths with `conda` and `airsenalenv` in them.
