### ISSUE TITLE
conda env create issues. numpyro error.

### ISSUE THREAD

**Issue by ricflairandy** [alan-turing-institute/AIrsenal#610]
When i run conda env create i get an error over the numpyro versioning:
The conflict is caused by:
    airsenal 1.6.1 depends on numpyro<0.10.0 and >=0.9.2
    bpl 0.2.0 depends on numpyro<0.13.0 and >=0.12.1

Cant proceed with the install insturctions at that point because i get :
ERROR: Could not find a version that satisfies the requirement airsenal (from versions: none)
ERROR: No matching distribution found for airsenal

I am using lunux subsystem on windows 11.

**Comment by jack89roberts** [comment]
Hi @ricflairandy , sorry it seems this broke after recent updates to the `bpl` package. We have a fix on our develop branch that should work, could you try this from the parent `AIrsenal` directory on your system:

```
git pull
git checkout develop
```

And then retry the installation as per the instructions in the readme?

**Comment by ricflairandy** [comment]
Legend, thats sorted. Thanks
