### ISSUE TITLE
TypeError on first run

### ISSUE THREAD

**Issue by attilathedunne** [alan-turing-institute/AIrsenal#617]
Hi, I'm getting the following error when running airsenal_run_prediction for the first time....

  File "/root/miniconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/utils.py", line 673, in list_players
    sort_order = case(value=PlayerAttributes.gameweek, whens=_whens)
TypeError: case() got an unexpected keyword argument 'whens'

Everything else has installed and ran ok

**Comment by jack89roberts** [comment]
Hi @attilathedunne , thanks for reporting this. I've pushed a fix, if you do 

```
git pull
conda activate airsenalenv
pip install --force-reinstall .
```

from where you cloned the AIrsenal repo it should work for you now.

**Comment by attilathedunne** [comment]
Thanks, working now!
