### ISSUE TITLE
Scripts to perform sanity checks on input data

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#62]
For start of 2019/20 season we had a hard-to-debug crash when initializing the player-level Stan model, which was traced back to an inconsistency in the player and match data for 2018/19  (for one playerscore row, nTeamGoals - numGoals - numAssists was -1) - this was eventually traced back to an incorrect gameweek in results_1819_with_gw.csv.   

But we should be able to debug this much faster - we should check for things like this in the DB after every upload.

**Comment by jack89roberts** [comment]
Started working on this in [feature/sanity_checks](https://github.com/alan-turing-institute/AIrsenal/tree/feature/sanity_checks) branch.
