### ISSUE TITLE
GT710 not detected

### ISSUE THREAD

**Issue by rohanday3** [alan-turing-institute/AIrsenal#635]
I have a GT 710 in an IBM x3400 M3 server but airsenal does not detect a gpu, what am i doing wrong?

lspci
15:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1)
15:00.1 Audio device: NVIDIA Corporation GK208 HDMI/DP Audio Controller (rev a1)

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by jack89roberts** [comment]
Is there a specific error you're getting? There may be some ideas to help in issue #632 

For what it's worth, you are very unlikely to see anything more than a tiny benefit from running AIrsenal on a GPU, and I'd guess there's a good chance it would actually be slower.

**Comment by rohanday3** [comment]
Oh wow okay thanks :)
