### ISSUE TITLE
Allow --max_transfers, --max_hit and --allow_unused options for airsenal_run_pipeline

### ISSUE THREAD

**Issue by iansealy** [alan-turing-institute/AIrsenal#636]
I sometimes can't bring myself to take the hit and make two transfers in a week when I only have one free transfer available. This minor edit adds the `--max_transfers` option to `airsenal_run_pipeline` and allows me to choose `--max_transfers 1` in those circumstances. Maybe it's useful to others too?

**Comment by jack89roberts** [comment]
Thanks for the contribution! There are a couple of other options in the optimisation that aren't exposed in the pipeline script at the moment, e.g.

```
  --max_hit MAX_HIT     maximum number of points to spend on additional transfers
  --allow_unused        if set, include strategies that waste free transfers
```

The `--max_hit` arg is also helpful for what you're talking about - it limits the total number of points hits taken across the strategy (in points, so 0, 4, 8, 12 for 0, 1, 2, 3 points hits etc.) Setting that to zero is maybe what you want more than limiting the no. transfers every week (as it will let you make 2 free transfers if you have them, or to save a transfer then use 2 at some point later in the strategy).

I think we should include the max transfers limit in your PR as well though (and if you're happy to add the two args above to the pipeline too that would be great, or we can do that separately).

**Comment by iansealy** [comment]
Thanks for the feedback @jack89roberts. I've added `--max_hit` and `--allow_unused` options to `airsenal_run_pipeline`. You're correct that `--max_hit` is the right choice for my use case. Thanks again.

**Comment by jack89roberts** [comment]
Thanks @iansealy , I've merged it to our develop branch so it will be included in the next AIrsenal release 🙂
