### ISSUE TITLE
[Bug] The "airsenal_make_transfers --confirm" command isn't applying changes to the lineup unless confirmed.

### ISSUE THREAD

**Issue by aaxyat** [alan-turing-institute/AIrsenal#638]
When I use the command "airsenal_make_transfers --confirm," the transfers apply correctly. However, the script asks for confirmation when making a lineup change.

**Comment by jack89roberts** [comment]
Thanks for reporting this @aaxyat - I think it should be fixed now if you pull the latest version and reinstall AIrsenal.
