### ISSUE TITLE
AIrsenal suggests transfers which result in a squad with too many of a position

### ISSUE THREAD

**Issue by sam-cutter** [alan-turing-institute/AIrsenal#652]
I just ran `airsenal_run_pipeline --weeks_ahead 3` for this gameweek and the program completed successfully. However, when I began to make the suggested transfers through the FPL website, I was unable to do so as the transfers would result in a team with 5 midfielders. I have 2 free transfers this week, although I doubt this is making a difference as the same issue occurred last week when I only had 1 free transfer.

My squad before:
![image](https://github.com/alan-turing-institute/AIrsenal/assets/66969418/4e68f467-f384-40d7-9ed3-092ed2e9a8db)

The transfers suggested:
```
Players in:                     Players out:
-----------                     ------------
Mohamed Salah                   James Maddison
Julián Álvarez                  Erling Haaland
```

I make these transfers in this order:
```
Maddison out
Haaland out
Salah in
Alvarez in
```
When trying to make the final transfer, I get the following message: `You already have the maximum number of Midfielders`.

Is there some way to get around this or does AIrsenal not know the rules of maximum numbers of players with a certain position?

**Comment by jack89roberts** [comment]
Hi @sam-cutter , these look like they should be valid to me - it's replacing a midfielder and a striker (Maddison and Haaland) with a cheaper midfielder and striker pair (Salah and J. Alvarez). Just to double check, there are two Alvarez in the game - one a West Ham midfielder (Edson Álvarez Velázquez) and another the Man City striker (Julián Álvarez). AIrsenal is suggesting you transfer in the Man City striker. Are you trying to transfer in the West Ham midfielder by accident?

Do you remember who the players were that caused the problem last week? You can also apply them automatically with AIrsenal using `airsenal_make_transfers` (but only use that if you haven't already made transfers manually).

**Comment by sam-cutter** [comment]
Ah, yes, you are correct. My bad!
