### ISSUE TITLE
Question: Will this work for the new season?

### ISSUE THREAD

**Issue by Savvasg35** [alan-turing-institute/AIrsenal#671]
Hello everyone this is more of a question. Does anyone know if this tool will work with the new season and any transfers that will happen in the summer?

**Comment by nbarlowATI** [comment]
Hi @Savvasg35!  Yes, we take all information about current players and teams from the FPL API itself, so as soon as that is up and running for the 2024-5 season, (or soon after...) we will make sure AIrsenal is ready to go.
