### ISSUE TITLE
24/25 season transfer and chips changes

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#679]
See https://www.premierleague.com/news/4058895

- Now can save up to 5 free transfers
- Playing chips doesn't reset saved free transfers (e.g. still can have 3 free transfers available the week after playing wildcard).
- A new "mystery chip" to be revealed January 2025
- Fewer double/blank gameweeks due to FA cup scheduling changes

Making it possible to consider strategies that make up to 5 transfers in a week probably would require quite substantial changes to the optimisation code to implement in full (and to implement in a way that runs in a reasonable amount of time).

First easier step is probably to update the logic around number of free transfers available (and the impact that has on points hits).

**Comment by Quasibzaar** [comment]
Any news on this one?

**Comment by jack89roberts** [comment]
There's a WIP PR (#680) but it has a bug we haven't figured out yet. I'll try to find some time to look at it soon.

**Comment by jack89roberts** [comment]
@Quasibzaar This is now working. If you pull the latest version of AIrsenal and reinstall you'll get the changes. The default is still to only consider a maximum of 2 transfers per week, but you can change that by setting `--max_transfers`. Allowing more than 2 transfers to be made will make the optimisation (much) slower and is unlikely to beat 2 transfer strategies as it falls back to random attempts (you can get it to try more options by increasing the value of `--num_iterations`.
