### ISSUE TITLE
Create & Update the code for the mini league 24-25 season

### ISSUE THREAD

**Issue by tshrjn** [alan-turing-institute/AIrsenal#685]
Seemly like we need to create & update the code (on the readme) for the mini league for 24-25 season.

**Comment by nbarlowATI** [comment]
Good point, thanks @tshrjn !   I just recreated the "Prem-AI League" mini-league - anyone who was in it before should automatically be re-entered, and for anyone new, the code to join is "yli1zg" - I'll put this on the README now.
