### ISSUE TITLE
Time of running Points Prediction& Optimization

### ISSUE THREAD

**Issue by negmeme2001** [alan-turing-institute/AIrsenal#696]
**I am trying to make a cron-job to run Points Prediction my question is what will be the best time to run these crons according to Is there any difference in doing this task whether it is right before the deadline or after the end of next week?**

**Meaning, we have now finished Game WeeK 11. Will there be a difference in the data between executing this task now or just before the deadline of the Game week 12 ?**

**Comment by nbarlowATI** [comment]
Hi @negmeme2001 ! For points prediction, it shouldn't make much difference whether you run just after the end of the previous gameweek, or the start of the next one - all the data on past team+player performance and future fixtures is already available at the start of that period (we don't currently use any data from e.g. midweek cup or European games).
The only possible difference is injury status - we take from the FPL API the information on each player's "chance of playing next gameweek".   This is fairly course-grained in FPL - it's either 25%, 50%, 75% or 100%, and we simplify it even further to say 50% or less is "not-going-to-play"(i.e. 0 predicted points), and 75% or more is can-play.     Where FPL gives an estimate of a player's expected return date, we also use this for the future few weeks' points predictions.

So, to get the points predictions including the most up-to-date injury status, it might be marginally better to run just before the next gameweek.
However, if you are doing a full optimization, including making player transfers, there can be an advantage to running this at the start of the between-gameweek-period, as player prices can change to reflect who other FPL managers are buying and selling.

Hope this helps!
