### ISSUE TITLE
Issue after wildcard

### ISSUE THREAD

**Issue by mazhar-debug** [alan-turing-institute/AIrsenal#85]
So it seems that it doesn't recognize that I've used the wildcard last week to do a lot of transfers, and is basing it's recommendations on a previous roster.

Any ideas on how to do fix?

Using the unique_playerid_violation branch.

**Comment by jack89roberts** [comment]
Have you run `update_airsenal_database` before doing the predictions and optimisation?

You can use the master branch now - it has the player violation fixes on it.

**Comment by mazhar-debug** [comment]
So I've remade the environment and now when running update_airsenal_database I get the following error:
Https://pastebin.com/vDQqu6q5

**Comment by jack89roberts** [comment]
Do you still get the error if you re-run these three steps?
```{bash}
> rm /tmp/data.db
> setup_airsenal_database
> update_airsenal_database
```

**Comment by mazhar-debug** [comment]
The database updates correctly, adding transfers from gw4. Running prediction and optimization now.

**Comment by mazhar-debug** [comment]
Nope, it's still suggesting players from players gw3 it seems. Doesn't take into account the wildcard I ran last week.

**Comment by jack89roberts** [comment]
Ok, I've given this the bug label and someone will look into it and/or suggest a workaround when we get a chance.

To summarise:
* Wildcard was played between GW3 and GW4.
* GW4 has been played.
* Predictions for GW5 are still using GW3 squad even though `update_airsenal_database` etc. run correctly (i.e. wildcard changes haven't been picked up).

**Comment by mazhar-debug** [comment]
That's right.

Would it mess up awfully if I jimmyfix the transaction-table and recreate my current team as gw1?

**Comment by nbarlowATI** [comment]
Hi,

_Would it mess up awfully if I jimmyfix the transaction-table and recreate my current team as gw1?_

it would probably work, but the biggest risk is that some of the prices would be wrong so you might not be able to afford the team it suggests for the next round...   
This is a strange issue, the only thing I can think of is that maybe FPL didn't mark gameweek 4 as "finished" for a few days after it actually was finished, which means the update script didn't look for the gameweek 4 data..  

A couple of suggestions for debugging:
In python terminal you can do something like:
```
>>> from airsenal.framework.utils import *
>>> get_last_finished_gameweek()  # should hopefully be 4
>>> get_players_for_gameweek(3) # should be list of player ids before wildcard
>>> get_players_for_gameweek(4) # should be list of player ids after wildcard
```
All these functions just use the FPL API directly, and don't depend on what is already in your database.
(Note that to get a player name from a player id you can do ```get_player_name(<playerID>)```)

You can query what you do have in your db by doing something like:
```
transactions = session.query(Transaction).order_by(Transaction.gameweek).all()
for t in transactions:
   print(t.gameweek, t.player_id, t.bought_or_sold)
```
to see if you do have anything from gameweek 4 in there.

Running ```update_airsenal_database``` should compare the output of ```get_players_for_gameweek(last_finished_gameweek)``` with what is in your db, and if they are not the same, it should fill the Transaction table with the latest transactions from the API.

I have just refactored this process a bit (removing scripts/fill_transaction_table.py and moving the functions to framework/transaction_utils.py) and made this process a bit more verbose, so it should now print out all the transactions as they are added to the database.   

Hope this helps a bit!

**Comment by jack89roberts** [comment]
I believe the changes made from #93 fix this issue so closing this.
