### ISSUE TITLE
Team is not complete due to unordered transactions from transactions table

### ISSUE THREAD

**Issue by danarwix** [alan-turing-institute/AIrsenal#91]
Hi,

While trying to run run_airsenal_optimization, I got "Team is incomplete" runtime error.
It happened due to unordered transactions while creating the current team and resolved in insufficient budget and inability to add a player.

My solution to the issue:
transactions = session.query(Transaction).order_by(Transaction.gameweek, Transaction.id).all()
In optimization_utils.get_starting_team

**Comment by jack89roberts** [comment]
Thanks @danarwix - I've replicated your problem and testing the fix now.

**Comment by danarwix** [comment]
In addition and with correlation to the same bug, I have found that the transactions table id column is not necessarily  by the order received by the API would like to add to my fix suggestion, the following fix:

    def get_fpl_transfer_data(self):
        """
        Get our transfer history from the FPL API.
        """
        ## return cached value if we already retrieved it.
        if self.fpl_transfer_history_data:
            return self.fpl_transfer_history_data
        ## or get it from the API.
        url = self.FPL_TEAM_TRANSFER_URL.format(self.FPL_TEAM_ID)
        r=requests.get(url)
        if not r.status_code == 200:
            print("Unable to access FPL transfer history API")
            return None
        self.fpl_transfer_history_data = list(reversed(json.loads(r.content.decode("utf-8"))))
        return self.fpl_transfer_history_data

The nature of the fix is to reverse the ordered list in order to get the right transfer history order

**Comment by jack89roberts** [comment]
Hi @danarwix - we've implemented your fixes and they're now in the master branch. Thanks for the suggestions!
