### ISSUE TITLE
interface providing win/lose/draw probabilities for match predictions

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#99]
It could be a nice feature to have a script/entrypoint and/or an API endpoint that can look at the bpl model's output for the upcoming weeks fixtures, and combine all the scoreline probabilities into home-win/ draw/ away-win probabilities.

**Comment by jack89roberts** [comment]
Fitted team models from BPL have a function `model.overall_probabilities(home_team, away_team)`, which does the work of combining the scoreline probabilities into overall home-win/draw/away-win probabilities, e.g. there is a cell using this in the [sandbox/team_model.ipynb](https://github.com/alan-turing-institute/AIrsenal/blob/master/sandbox/team_model.ipynb) notebook.

I think with a bit of guidance this could be a good first issue so adding the label. The idea would be to make a function that: 
* Fits a team model (or uses a previously fitted model if we've done #80).
* Gets the home and away teams for all fixtures in a given gameweek.
* Calls `model.overall_probabilities(home_team, away_team)` on all those fixtures.
* Returns probabilities for all fixtures, maybe as a data frame with a row for each fixture and columns being fixture_id, home_team, away_team, home_win_probability, draw_probability, away_win_probability.

But should expand a bit on where to get started with the above to make it genuinely a good first issue.

**Comment by jack89roberts** [comment]
Function can go in `framework/api_utils.py`, ideally with an endpoint that calls it in `api/app.py`.

**Comment by chiefsan** [comment]
My shot at writing the function: https://github.com/chiefsan/AIrsenal/blob/8a2bd1a1b68b3229b2dae5cfbfe0d7ab9b7ec93d/airsenal/framework/api_utils.py#L301
Shall I keep the name `fixture_probabilities` or change it?
I haven't added an endpoint in `api/app.py` because I don't yet understand how those decorators and everything else works. None of the functions had any references in any other files. Why? Am I using them elsewhere without realizing it?

**Comment by jack89roberts** [comment]
Hi @chiefsan ,

I haven't tried to run it yet but looks good, thanks! The API parts of the code are currently a work in progress aimed at making a dashboard people can interact with - the dashboard is in a different repo (https://github.com/alan-turing-institute/airsenal-frontend) so there are not many references to the API functions in this repo.

This function will probably be useful in general though, not just for the API, so `airsenal/framework/utils.py` might actually be a better place for it.

Could you make a pull request for it? Then we can review it properly.

Thanks!
Jack
